(() => {
  const games = window.WWG_GAMES || [];
  const load = (k, fallback) => { try { return JSON.parse(localStorage.getItem(k) || JSON.stringify(fallback)); } catch { return fallback; } };
  const today = new Date().toLocaleDateString('en-CA');
  const dailyStore = load('wwg:daily', {});
  const day = dailyStore[today] || { plays: 0, unique: [], brain: 0, milestones: 0, ratings: 0, eventKeys: [] };
  const state = {
    query: '', category: 'All', input: 'All', mode: 'All', status: 'All', collection: 'All', sort: 'featured',
    favorites: load('wwg:favorites', []), recent: load('wwg:recent', []), plays: load('wwg:plays', {}),
    ratings: load('wwg:ratings', {}), events: load('wwg:events', {}), scores: load('wwg:scores', {}), runs: load('wwg:score-runs', {}), runHistory: load('wwg:run-history', []), playtime: load('wwg:playtime', {}), sessions: load('wwg:sessions', {}), dailyPlaytime: load('wwg:daily-playtime', {}), dailyGamePlaytime: load('wwg:daily-game-playtime', {}),
    prefs: load('wwg:prefs', { reducedMotion: false, muted: false, volume: 0.7, highContrast: false, textScale: 1 }), keymap: load('wwg:keymap', {})
  };
  const $ = s => document.querySelector(s);
  const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const categories = ['All', ...new Set(games.flatMap(g => g.genres))];
  const fmt = d => new Date(d + 'T12:00:00').toLocaleDateString(undefined, { month:'short', day:'numeric', year:'numeric' });
  const totalPlays = () => Object.values(state.plays).reduce((a,b)=>a+Number(b||0),0);
  const uniquePlays = () => Object.keys(state.plays).filter(k=>state.plays[k]>0 && games.some(g=>g.id===k)).length;
  const milestoneCount = () => Object.values(state.events).reduce((a,b)=>a+Number(b||0),0);
  const scoreCount = () => Object.keys(state.scores).filter(k=>Number.isFinite(Number(state.scores[k]))).length;
  const runCount = () => Array.isArray(state.runHistory)?state.runHistory.length:Object.keys(state.runs).length;
  const milestoneGames = () => new Set(Object.keys(state.events).filter(k=>Number(state.events[k])>0).map(k=>k.split(':')[0])).size;
  const clearedGames = () => new Set(Object.keys(state.events).filter(k=>Number(state.events[k])>0).map(k=>k.split(':')[0]).filter(id=>games.some(g=>g.id===id))).size;
  const bestScore = () => Math.max(0, ...Object.values(state.scores).map(Number).filter(Number.isFinite));
  const totalPlaySeconds = () => Object.values(state.playtime).reduce((a,b)=>a+Number(b||0),0); const totalSessions=()=>Object.values(state.sessions).reduce((a,b)=>a+Number(b?.count||0),0); const longestSession=()=>Math.max(0,...Object.values(state.sessions).map(v=>Number(v?.longest||0))); const topPlayGenre=()=>{const totals={};for(const g of games){const sec=Number(state.playtime[g.id]||0);for(const genre of g.genres)totals[genre]=(totals[genre]||0)+sec}return Object.entries(totals).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—'};
  const playMinutes = id => Math.floor(Number(state.playtime[id]||0)/60);
  function recentGenreTotals(){const totals={};for(let i=0;i<7;i++){const d=new Date(today+'T12:00:00');d.setDate(d.getDate()-i);const dayMap=state.dailyGamePlaytime[d.toLocaleDateString('en-CA')]||{};for(const [id,sec] of Object.entries(dayMap)){const g=games.find(x=>x.id===id);if(!g)continue;for(const genre of g.genres)totals[genre]=(totals[genre]||0)+Number(sec||0)}}return totals}const recentGenreCount=()=>Object.values(recentGenreTotals()).filter(v=>v>0).length;
  const collections={All:()=>true,'Quick Runs':g=>g.genres.some(x=>['Arcade','Puzzle','Word','Typing','Pinball','Rhythm'].includes(x)),'Strategy Desk':g=>g.genres.some(x=>['Strategy','Tactical','Turn-Based','Card','Deckbuilder'].includes(x)),'Local Together':g=>g.genres.some(x=>['Multiplayer','Co-op'].includes(x)),'Explore Worlds':g=>g.genres.some(x=>['Exploration','RPG','Survival','Space','Underwater','Dungeon','Nature'].includes(x)),'Creative Systems':g=>g.genres.some(x=>['Simulation','Sandbox','Automation','Programming','City Builder','Colony'].includes(x)),'Slow & Cozy':g=>g.genres.some(x=>['Relaxing','Fishing','Ecology','Photography','Nature'].includes(x)),'Mind Games':g=>g.genres.some(x=>['Deduction','Mystery','Logic','Programming','Observation','Time Loop'].includes(x)),'Story & Journey':g=>g.genres.some(x=>['Narrative','Interactive Fiction','Adventure'].includes(x)),'Skill & Timing':g=>g.genres.some(x=>['Cooking','Time Management','Rhythm','Sports','Racing','Pinball','Typing','Memory'].includes(x)),'Hands & Heart':g=>g.genres.some(x=>['Rescue','Emergency','Farming','Agriculture','Ecology','Nature'].includes(x)),'Build & Operate':g=>g.genres.some(x=>['Construction','Engineering','Vehicle Simulation','Transit','Logistics','City Builder','Automation'].includes(x)),'Aim & Arc':g=>g.genres.some(x=>['Golf','Precision','Pinball','Physics','Sports'].includes(x))};
  const startOfWeek = (()=>{const d=new Date(today+'T12:00:00'),dayNum=(d.getDay()+6)%7;d.setDate(d.getDate()-dayNum);return d.toLocaleDateString('en-CA')})();
  function weekAggregate(){const start=new Date(startOfWeek+'T12:00:00'),unique=new Set();let plays=0,brain=0,milestones=0,ratings=0,circuits=0;for(let i=0;i<7;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=d.toLocaleDateString('en-CA'),rec=dailyStore[key];if(!rec)continue;plays+=Number(rec.plays||0);brain+=Number(rec.brain||0);milestones+=Number(rec.milestones||0);ratings+=Number(rec.ratings||0);for(const id of rec.unique||[])unique.add(id);if(dailyCompleteFor(key,rec)===3)circuits++;}return{plays,unique:unique.size,brain,milestones,ratings,circuits}}
  function capabilities(g){const c=(g.controls||[]).join(' ').toLowerCase(),out=[];if(/wasd|arrow|keyboard|digit|space|key/.test(c))out.push('Keyboard');if(/touch|tap|mobile|pointer|click/.test(c))out.push('Touch');if(/gamepad/.test(c))out.push('Gamepad');if(g.remappable)out.push('Remappable');return out;}
  function playModes(g){if(Array.isArray(g.modes)&&g.modes.length)return g.modes;return g.genres.some(x=>['Multiplayer','Co-op'].includes(x))?['Local Multiplayer']:['Solo'];}
  const challengePool = [
    { id:'double-header', name:'Double Header', desc:'Play 2 different games today.', metric:'unique', goal:2 },
    { id:'triple-jump', name:'Triple Jump', desc:'Launch 3 games today.', metric:'plays', goal:3 },
    { id:'brain-run', name:'Brain Run', desc:'Launch a Puzzle or Strategy game today.', metric:'brain', goal:1 },
    { id:'milestone-spark', name:'Milestone Spark', desc:'Complete 1 supported in-game milestone today.', metric:'milestones', goal:1 },
    { id:'signal-critic', name:'Signal Critic', desc:'Rate a game today.', metric:'ratings', goal:1 },
    { id:'variety-lap', name:'Variety Lap', desc:'Play 3 different games today.', metric:'unique', goal:3 },
    { id:'long-circuit', name:'Long Circuit', desc:'Launch 5 games today.', metric:'plays', goal:5 },
    { id:'double-spark', name:'Double Spark', desc:'Complete 2 supported milestones today.', metric:'milestones', goal:2 }
  ];
  const metricValue = (c,d) => c.metric==='unique' ? (Array.isArray(d?.unique)?d.unique.length:0) : Number(d?.[c.metric]||0);
  function challengeSet(date){ let seed=0; for(const ch of date) seed=(seed*31+ch.charCodeAt(0))>>>0; const out=[], used=new Set(); while(out.length<3){ seed=(seed*1664525+1013904223)>>>0; const i=seed%challengePool.length; if(!used.has(i)){used.add(i);out.push(challengePool[i]);} } return out; }
  const dailyChallenges = challengeSet(today);
  const dailyCompleteFor = (date,d) => challengeSet(date).filter(c=>metricValue(c,d)>=c.goal).length;
  const dailyComplete = () => dailyCompleteFor(today,day);
  const weeklyPool=[
    {id:'weekly-plays',name:'Long Haul',desc:'Launch 12 games this week.',metric:'plays',goal:12},
    {id:'weekly-variety',name:'World Sampler',desc:'Play 6 different games this week.',metric:'unique',goal:6},
    {id:'weekly-brain',name:'Strategist Week',desc:'Play Puzzle or Strategy games on 3 days.',metric:'brain',goal:3},
    {id:'weekly-sparks',name:'Milestone Trail',desc:'Record 4 in-game milestones this week.',metric:'milestones',goal:4},
    {id:'weekly-ratings',name:'Curator',desc:'Rate 3 games this week.',metric:'ratings',goal:3},
    {id:'weekly-circuits',name:'Circuit Pair',desc:'Complete the full Daily Circuit twice this week.',metric:'circuits',goal:2}
  ];
  function weeklySet(){let seed=0;for(const ch of startOfWeek)seed=(seed*33+ch.charCodeAt(0))>>>0;const out=[],used=new Set();while(out.length<4){seed=(seed*1103515245+12345)>>>0;const i=seed%weeklyPool.length;if(!used.has(i)){used.add(i);out.push(weeklyPool[i])}}return out}
  const weeklyChallenges=weeklySet();
  const weeklyComplete=()=>{const a=weekAggregate();return weeklyChallenges.filter(c=>Number(a[c.metric]||0)>=c.goal).length};
  function challengeStreak(){ let cursor=new Date(today+'T12:00:00'); if(dailyComplete()<3) cursor.setDate(cursor.getDate()-1); let count=0; for(let i=0;i<365;i++){const key=cursor.toLocaleDateString('en-CA'),d=dailyStore[key];if(!d||dailyCompleteFor(key,d)<3)break;count++;cursor.setDate(cursor.getDate()-1)}return count; }
  const achievements = [
    {id:'first-launch',name:'First Launch',desc:'Play your first WorldWideGames release.',test:()=>totalPlays()>=1,progress:()=>Math.min(1,totalPlays())+'/1'},
    {id:'genre-hopper',name:'Genre Hopper',desc:'Play four different games.',test:()=>uniquePlays()>=4,progress:()=>Math.min(4,uniquePlays())+'/4'},
    {id:'pathfinder',name:'Pathfinder',desc:'Play ten different games.',test:()=>uniquePlays()>=10,progress:()=>Math.min(10,uniquePlays())+'/10'},
    {id:'collector',name:'Collector',desc:'Favorite three games.',test:()=>state.favorites.length>=3,progress:()=>Math.min(3,state.favorites.length)+'/3'},
    {id:'critic',name:'Local Critic',desc:'Rate three games.',test:()=>Object.keys(state.ratings).length>=3,progress:()=>Math.min(3,Object.keys(state.ratings).length)+'/3'},
    {id:'regular',name:'Arcade Regular',desc:'Reach 15 total local plays.',test:()=>totalPlays()>=15,progress:()=>Math.min(15,totalPlays())+'/15'},
    {id:'milestones',name:'Milestone Hunter',desc:'Complete three supported in-game milestones.',test:()=>milestoneCount()>=3,progress:()=>Math.min(3,milestoneCount())+'/3'},
    {id:'world-tour',name:'World Tour',desc:'Play every current game in the catalog.',test:()=>uniquePlays()>=games.length,progress:()=>Math.min(games.length,uniquePlays())+'/'+games.length},
    {id:'score-setter',name:'Score Setter',desc:'Post a local score from a supported game.',test:()=>scoreCount()>=1,progress:()=>Math.min(1,scoreCount())+'/1'},
    {id:'score-chaser',name:'Score Chaser',desc:'Record a local best score of 1,000 or more.',test:()=>bestScore()>=1000,progress:()=>Math.min(1000,bestScore()).toLocaleString()+'/1,000'},
    {id:'daily-triple',name:'Daily Triple',desc:'Complete all three Daily Circuit goals.',test:()=>dailyComplete()===3,progress:()=>dailyComplete()+'/3'},
    {id:'circuit-streak',name:'Circuit Streak',desc:'Complete the Daily Circuit on 3 consecutive days.',test:()=>challengeStreak()>=3,progress:()=>Math.min(3,challengeStreak())+'/3 days'},
    {id:'deep-catalog',name:'Deep Catalog',desc:'Play fifteen different WorldWideGames releases.',test:()=>uniquePlays()>=15,progress:()=>Math.min(15,uniquePlays())+'/15'},
    {id:'week-circuit',name:'Circuit Veteran',desc:'Complete the Daily Circuit on 7 consecutive days.',test:()=>challengeStreak()>=7,progress:()=>Math.min(7,challengeStreak())+'/7 days'},
    {id:'milestone-tour',name:'Milestone Tour',desc:'Record milestones in eight different games.',test:()=>milestoneGames()>=8,progress:()=>Math.min(8,milestoneGames())+'/8 games'},
    {id:'weekly-explorer',name:'Weekly Explorer',desc:'Complete two Weekly Circuit goals.',test:()=>weeklyComplete()>=2,progress:()=>Math.min(2,weeklyComplete())+'/2'},
    {id:'weekly-master',name:'Weekly Master',desc:'Complete all four Weekly Circuit goals.',test:()=>weeklyComplete()===4,progress:()=>weeklyComplete()+'/4'},
    {id:'dispatcher',name:'Master Dispatcher',desc:'Complete a Railspire Dispatch shift.',test:()=>Number(state.events['railspire-dispatch:shift-complete']||0)>0,progress:()=>Number(state.events['railspire-dispatch:shift-complete']||0)>0?'1/1':'0/1'},
    {id:'wordsmith',name:'Wordsmith',desc:'Seal a Glyphsmith archive.',test:()=>Number(state.events['glyphsmith:forge-complete']||0)>0,progress:()=>Number(state.events['glyphsmith:forge-complete']||0)>0?'1/1':'0/1'},
    {id:'system-architect',name:'System Architect',desc:'Complete a Solar Loom system.',test:()=>Number(state.events['solar-loom:system-complete']||0)>0,progress:()=>Number(state.events['solar-loom:system-complete']||0)>0?'1/1':'0/1'},
    {id:'abyss-listener',name:'Abyss Listener',desc:'Complete a Deepwater Signal mission.',test:()=>Number(state.events['deepwater-signal:mission-complete']||0)>0,progress:()=>Number(state.events['deepwater-signal:mission-complete']||0)>0?'1/1':'0/1'},
    {id:'deck-pilgrim',name:'Deck Pilgrim',desc:'Reach the Emberdeck shrine.',test:()=>Number(state.events['emberdeck-pilgrim:pilgrimage-complete']||0)>0,progress:()=>Number(state.events['emberdeck-pilgrim:pilgrimage-complete']||0)>0?'1/1':'0/1'},
    {id:'logic-gardener',name:'Logic Gardener',desc:'Complete all Command Bloom programs.',test:()=>Number(state.events['command-bloom:program-complete']||0)>0,progress:()=>Number(state.events['command-bloom:program-complete']||0)>0?'1/1':'0/1'},
    {id:'hour-one',name:'Hour One',desc:'Spend one hour playing WorldWideGames locally.',test:()=>totalPlaySeconds()>=3600,progress:()=>Math.min(60,Math.floor(totalPlaySeconds()/60))+'/60 min'},
    {id:'wind-courier',name:'Wind Courier',desc:'Complete all four Windward Cargo deliveries.',test:()=>Number(state.events['windward-cargo:route-complete']||0)>0,progress:()=>Number(state.events['windward-cargo:route-complete']||0)>0?'1/1':'0/1'},
    {id:'cipher-sleuth',name:'Cipher Sleuth',desc:'Close the full Cipher Court docket.',test:()=>Number(state.events['cipher-court:docket-solved']||0)>0,progress:()=>Number(state.events['cipher-court:docket-solved']||0)>0?'1/1':'0/1'},
    {id:'moon-angler',name:'Moon Angler',desc:'Complete a Moonwake Angler night haul.',test:()=>Number(state.events['moonwake-angler:night-haul']||0)>0,progress:()=>Number(state.events['moonwake-angler:night-haul']||0)>0?'1/1':'0/1'},
    {id:'session-runner',name:'Session Runner',desc:'Start 20 local game sessions.',test:()=>totalSessions()>=20,progress:()=>Math.min(20,totalSessions())+'/20'},
    {id:'caravan-keeper',name:'Caravan Keeper',desc:'Complete an Ashfall Caravan journey.',test:()=>Number(state.events['ashfall-caravan:journey-complete']||0)>0,progress:()=>Number(state.events['ashfall-caravan:journey-complete']||0)>0?'1/1':'0/1'},
    {id:'twinforge-team',name:'Twinforge Team',desc:'Complete a Twinforge Expedition.',test:()=>Number(state.events['twinforge-expedition:expedition-complete']||0)>0,progress:()=>Number(state.events['twinforge-expedition:expedition-complete']||0)>0?'1/1':'0/1'},
    {id:'museum-eye',name:'Museum Eye',desc:'Close the Mothlight Museum case.',test:()=>Number(state.events['mothlight-museum:case-closed']||0)>0,progress:()=>Number(state.events['mothlight-museum:case-closed']||0)>0?'1/1':'0/1'},
    {id:'active-week',name:'Active Week',desc:'Play on five different local days.',test:()=>Object.keys(state.dailyPlaytime).filter(k=>Number(state.dailyPlaytime[k]||0)>0).length>=5,progress:()=>Math.min(5,Object.keys(state.dailyPlaytime).filter(k=>Number(state.dailyPlaytime[k]||0)>0).length)+'/5 days'},
    {id:'run-logger',name:'Run Logger',desc:'Record ten scored runs in local history.',test:()=>runCount()>=10,progress:()=>Math.min(10,runCount())+'/10'},
    {id:'fold-keeper',name:'Fold Keeper',desc:'Deliver the Chronofold archive.',test:()=>Number(state.events['chronofold-courier:archive-delivered']||0)>0,progress:()=>Number(state.events['chronofold-courier:archive-delivered']||0)>0?'1/1':'0/1'},
    {id:'hearthline-chef',name:'Hearthline Chef',desc:'Complete a Hearthline Kitchen service.',test:()=>Number(state.events['hearthline-kitchen:service-complete']||0)>0,progress:()=>Number(state.events['hearthline-kitchen:service-complete']||0)>0?'1/1':'0/1'},
    {id:'field-photographer',name:'Field Photographer',desc:'Complete a Spectra Safari survey.',test:()=>Number(state.events['spectra-safari:survey-complete']||0)>0,progress:()=>Number(state.events['spectra-safari:survey-complete']||0)>0?'1/1':'0/1'},
    {id:'genre-week',name:'Genre Week',desc:'Spend local playtime in five genres within seven days.',test:()=>recentGenreCount()>=5,progress:()=>Math.min(5,recentGenreCount())+'/5 genres'},
    {id:'two-hour-club',name:'Two Hour Club',desc:'Spend two hours playing WorldWideGames locally.',test:()=>totalPlaySeconds()>=7200,progress:()=>Math.min(120,Math.floor(totalPlaySeconds()/60))+'/120 min'},
    {id:'rescue-captain',name:'Rescue Captain',desc:'Clear a Frostline Rescue district.',test:()=>Number(state.events['frostline-rescue:district-cleared']||0)>0,progress:()=>Number(state.events['frostline-rescue:district-cleared']||0)>0?'1/1':'0/1'},
    {id:'signal-keeper',name:'Signal Keeper',desc:'Synchronize the full Signal Choir.',test:()=>Number(state.events['signal-choir:choir-complete']||0)>0,progress:()=>Number(state.events['signal-choir:choir-complete']||0)>0?'1/1':'0/1'},
    {id:'terrace-steward',name:'Terrace Steward',desc:'Fulfill a Terrace Keeper seasonal contract.',test:()=>Number(state.events['terrace-keeper:season-complete']||0)>0,progress:()=>Number(state.events['terrace-keeper:season-complete']||0)>0?'1/1':'0/1'},
    {id:'key-crafter',name:'Key Crafter',desc:'Save a custom keyboard control map.',test:()=>Object.keys(state.keymap||{}).length>0,progress:()=>Object.keys(state.keymap||{}).length>0?'1/1':'0/1'},
    {id:'spanwright-certified',name:'Spanwright Certified',desc:'Certify all five Spanwright blueprints.',test:()=>Number(state.events['spanwright:grand-span-certified']||0)>0,progress:()=>Number(state.events['spanwright:grand-span-certified']||0)>0?'1/1':'0/1'},
    {id:'night-operator',name:'Night Operator',desc:'Complete a Lantern Line city-loop service.',test:()=>Number(state.events['lantern-line:route-complete']||0)>0,progress:()=>Number(state.events['lantern-line:route-complete']||0)>0?'1/1':'0/1'},
    {id:'precision-service',name:'Precision Service',desc:'Finish Lantern Line with 20 seconds of service delay or less.',test:()=>Number.isFinite(Number(state.scores['lantern-line']))&&Number(state.scores['lantern-line'])<=20,progress:()=>Number.isFinite(Number(state.scores['lantern-line']))?Math.min(20,Number(state.scores['lantern-line']))+' sec':'—'},
    {id:'links-finisher',name:'Links Finisher',desc:'Complete all six Driftglass Links holes.',test:()=>Number(state.events['driftglass-links:course-complete']||0)>0,progress:()=>Number(state.events['driftglass-links:course-complete']||0)>0?'1/1':'0/1'},
    {id:'tide-cartographer',name:'Tide Cartographer',desc:'Seal the complete Tideglass Surveyor atlas.',test:()=>Number(state.events['tideglass-surveyor:survey-complete']||0)>0,progress:()=>Number(state.events['tideglass-surveyor:survey-complete']||0)>0?'1/1':'0/1'},
    {id:'prism-soloist',name:'Prism Soloist',desc:'Defeat the Prism Duel AI in a first-to-five match.',test:()=>Number(state.events['prism-duel:ai-duel-won']||0)>0,progress:()=>Number(state.events['prism-duel:ai-duel-won']||0)>0?'1/1':'0/1'},
    {id:'clear-twenty',name:'Twenty Clears',desc:'Record completion milestones in twenty different games.',test:()=>clearedGames()>=20,progress:()=>Math.min(20,clearedGames())+'/20 games'},
    {id:'clear-forty',name:'Catalog Master',desc:'Record completion milestones in forty different games.',test:()=>clearedGames()>=40,progress:()=>Math.min(40,clearedGames())+'/40 games'}
  ];
  function applyPrefs(){ document.documentElement.classList.toggle('reduced-motion', !!state.prefs.reducedMotion); document.documentElement.classList.toggle('high-contrast', !!state.prefs.highContrast); const scale=Math.max(.9,Math.min(1.25,Number(state.prefs.textScale)||1)); document.documentElement.style.setProperty('--wwg-text-scale',scale); document.documentElement.classList.toggle('text-scaled',Math.abs(scale-1)>.001); }
  applyPrefs();
  function isNew(g){ const age=(Date.now()-new Date(g.added+'T12:00:00').getTime())/86400000; return age>=0&&age<=7; }
  function ratingText(g){ const r=Number(state.ratings[g.id]||0); return r?`★ ${r}/5`:'Unrated'; }
  function gameCard(g, mini=false) {
    const plays=state.plays[g.id]||0, mins=playMinutes(g.id), fav=state.favorites.includes(g.id), score=state.scores[g.id], cleared=Object.keys(state.events).some(k=>k.startsWith(g.id+':')&&Number(state.events[k])>0);
    return `<article class="game-card ${mini?'mini':''}" data-id="${g.id}"><a class="cover-link" href="game.html?id=${encodeURIComponent(g.id)}" aria-label="Play ${esc(g.title)}"><img src="${g.cover}" alt="${esc(g.title)} cover art" /></a><div class="card-body"><div class="card-topline"><span>${isNew(g)?'<b class="new-badge">NEW</b> ':''}${cleared?'<b class="clear-badge">CLEARED</b> ':''}${esc(g.genres[0])}</span><button class="favorite ${fav?'active':''}" data-favorite="${g.id}" aria-label="${fav?'Remove from':'Add to'} favorites">${fav?'♥':'♡'}</button></div><h3><a href="game.html?id=${encodeURIComponent(g.id)}">${esc(g.title)}</a></h3>${mini?'':`<p>${esc(g.tagline)}</p>`}<div class="card-meta"><span>${plays?plays+' local play'+(plays===1?'':'s'):'Ready to play'}${mins?' / '+mins+' min':''}</span><span>${score!=null?'Best '+Number(score).toLocaleString()+' '+esc(g.scoreMeta?.unit||'pts')+(g.scoreMeta?.direction==='low'?' ↓':''):ratingText(g)}</span>${mini?'':`<span>${fmt(g.added)}</span>`}</div>${mini?'':`<div class="cap-row">${[...capabilities(g),...playModes(g)].map(x=>`<span>${x}</span>`).join('')}</div>`}</div></article>`;
  }
  function renderLibrary(){ const cleared=g=>Object.keys(state.events).some(k=>k.startsWith(g.id+':')&&Number(state.events[k])>0); let list=games.filter(g=>(state.category==='All'||g.genres.includes(state.category))&&(state.input==='All'||capabilities(g).includes(state.input))&&(state.mode==='All'||playModes(g).includes(state.mode))&&(state.collection==='All'||(collections[state.collection]||collections.All)(g))&&(state.status==='All'||(state.status==='Unplayed'&&!state.plays[g.id])||(state.status==='Favorites'&&state.favorites.includes(g.id))||(state.status==='Cleared'&&cleared(g)))&&(`${g.title} ${g.tagline} ${g.description} ${g.genres.join(' ')}`).toLowerCase().includes(state.query.toLowerCase())); list.sort((a,b)=>state.sort==='new'?b.added.localeCompare(a.added)||b.basePopularity-a.basePopularity:state.sort==='popular'?(b.basePopularity+(state.plays[b.id]||0)*3)-(a.basePopularity+(state.plays[a.id]||0)*3):state.sort==='rated'?(state.ratings[b.id]||0)-(state.ratings[a.id]||0)||b.basePopularity-a.basePopularity:state.sort==='time'?(Number(state.playtime[b.id]||0)-Number(state.playtime[a.id]||0)||b.basePopularity-a.basePopularity):state.sort==='az'?a.title.localeCompare(b.title):Number(b.featured)-Number(a.featured)||b.basePopularity-a.basePopularity); $('#gameGrid').innerHTML=list.map(g=>gameCard(g)).join(''); $('#emptyState').hidden=!!list.length; wireFavorites(); }
  function renderChips(){ $('#categoryChips').innerHTML=categories.map(c=>`<button class="chip ${c===state.category?'active':''}" data-category="${esc(c)}">${esc(c)}</button>`).join(''); document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>{state.category=b.dataset.category;renderChips();renderLibrary();})); }
  function wireFavorites(){ document.querySelectorAll('[data-favorite]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();const id=b.dataset.favorite;state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];localStorage.setItem('wwg:favorites',JSON.stringify(state.favorites));renderLibrary();renderPersonal();renderRecommendations();})); }
  function renderAchievements(){ const unlocked=achievements.filter(a=>a.test()).length; $('#achievementGrid').innerHTML=achievements.map(a=>`<div class="achievement ${a.test()?'unlocked':''}"><span class="achievement-icon">${a.test()?'◆':'◇'}</span><div><strong>${esc(a.name)}</strong><small>${esc(a.desc)}</small><em>${a.progress()}</em></div></div>`).join(''); return unlocked; }
  function renderScores(){ const list=Object.entries(state.scores).map(([id,v])=>({game:games.find(g=>g.id===id),score:Number(v),at:String(state.runs[id]?.at||'')})).filter(x=>x.game&&Number.isFinite(x.score)).sort((a,b)=>b.at.localeCompare(a.at)||a.game.title.localeCompare(b.game.title)).slice(0,8); $('#scoreBoard').innerHTML=list.length?list.map((x,i)=>`<a class="score-row" href="game.html?id=${encodeURIComponent(x.game.id)}"><span><b>${i+1}</b>${esc(x.game.title)}<small>${x.game.scoreMeta?.direction==='low'?'lower is better':'higher is better'}</small></span><strong>${x.score.toLocaleString()} ${esc(x.game.scoreMeta?.unit||'pts')} ${x.game.scoreMeta?.direction==='low'?'↓':'↑'}</strong></a>`).join(''):'<p class="muted">Supported games will post local best scores here.</p>'; const rawRuns=Array.isArray(state.runHistory)&&state.runHistory.length?state.runHistory:Object.entries(state.runs).map(([id,r])=>({id,...r}));const runs=rawRuns.map(r=>({game:games.find(g=>g.id===r.id),r})).filter(x=>x.game&&x.r&&Number.isFinite(Number(x.r.score))).sort((a,b)=>String(b.r.at||'').localeCompare(String(a.r.at||''))).slice(0,8);if($('#runHistory'))$('#runHistory').innerHTML=runs.length?runs.map(x=>`<a class="score-row run-row" href="game.html?id=${encodeURIComponent(x.game.id)}"><span>${esc(x.game.title)}<small>${esc(String(x.r.event||'run').replaceAll('-', ' '))}${Number.isFinite(Number(x.r.duration))?` • ${Number(x.r.duration).toLocaleString()}s`:''}</small></span><strong>${Number(x.r.score).toLocaleString()} ${esc(x.game.scoreMeta?.unit||'pts')}</strong></a>`).join(''):'<p class="muted">Your latest scored runs will appear here with event and duration metadata when available.</p>'; }

  function renderActivity(){const el=$('#activityChart');if(!el)return;const days=[];for(let i=6;i>=0;i--){const d=new Date(today+'T12:00:00');d.setDate(d.getDate()-i);const key=d.toLocaleDateString('en-CA'),sec=Number(state.dailyPlaytime[key]||0);days.push({key,label:d.toLocaleDateString(undefined,{weekday:'short'}),min:Math.floor(sec/60)})}const max=Math.max(1,...days.map(d=>d.min));el.innerHTML=days.map(d=>`<div class="activity-day" title="${esc(d.key)} · ${d.min} min"><span>${d.min?d.min+'m':'—'}</span><i style="height:${Math.max(4,Math.round(d.min/max*64))}px"></i><b>${esc(d.label)}</b></div>`).join('')}
  function renderGenreTrends(){const el=$('#genreTrends');if(!el)return;const list=Object.entries(recentGenreTotals()).filter(x=>x[1]>0).sort((a,b)=>b[1]-a[1]).slice(0,5),max=Math.max(1,...list.map(x=>x[1]));el.innerHTML=list.length?list.map(([genre,sec])=>`<div class="genre-trend"><span>${esc(genre)}</span><i style="width:${Math.max(6,Math.round(sec/max*100))}%"></i><b>${Math.max(1,Math.floor(sec/60))}m</b></div>`).join(''):'<p class="muted">Play games this week to build a private genre activity map.</p>';}
  function renderChallenges(){ const complete=dailyComplete(), streak=challengeStreak(); $('#challengeGrid').innerHTML=dailyChallenges.map(c=>{const v=Math.min(c.goal,metricValue(c,day)),done=v>=c.goal;return `<article class="challenge-card ${done?'complete':''}"><span class="challenge-mark">${done?'✓':'◇'}</span><div><strong>${esc(c.name)}</strong><p>${esc(c.desc)}</p><div class="challenge-progress"><i style="width:${Math.round(v/c.goal*100)}%"></i></div><small>${v}/${c.goal}</small></div></article>`}).join(''); $('#challengeNote').textContent=complete===3?`Daily circuit complete • ${Math.max(1,streak)} day streak.`:`${complete}/3 complete • current streak ${streak} day${streak===1?'':'s'}.`; if($('#streakPanel')) $('#streakPanel').innerHTML=`<strong>${streak}</strong><span>consecutive completed circuit day${streak===1?'':'s'}</span><small>Today's rotating set is generated locally and changes each day.</small>`; }
  function renderWeekly(){const agg=weekAggregate(),done=weeklyComplete();if(!$('#weeklyGrid'))return;$('#weeklyGrid').innerHTML=weeklyChallenges.map(c=>{const v=Math.min(c.goal,Number(agg[c.metric]||0)),ok=v>=c.goal;return `<article class="challenge-card weekly-card ${ok?'complete':''}"><span class="challenge-mark">${ok?'✓':'◇'}</span><div><strong>${esc(c.name)}</strong><p>${esc(c.desc)}</p><div class="challenge-progress"><i style="width:${Math.round(v/c.goal*100)}%"></i></div><small>${v}/${c.goal}</small></div></article>`}).join('');$('#weeklyNote').textContent=done===4?'Weekly Circuit complete.':`${done}/4 complete • resets with the next local week.`;}
  function renderPersonal(){ const recent=state.recent.map(id=>games.find(g=>g.id===id)).filter(Boolean).slice(0,3), favs=state.favorites.map(id=>games.find(g=>g.id===id)).filter(Boolean).slice(0,3); $('#recentGrid').innerHTML=recent.length?recent.map(g=>gameCard(g,true)).join(''):'<p class="muted">Play a game and it will appear here.</p>'; $('#favoriteGrid').innerHTML=favs.length?favs.map(g=>gameCard(g,true)).join(''):'<p class="muted">Tap ♡ on a game to save it here.</p>'; wireFavorites(); const unlocked=renderAchievements(); renderScores(); renderWeekly(); renderActivity(); renderGenreTrends(); $('#profileStats').innerHTML=`<div><strong>${totalPlays()}</strong><span>local plays</span></div><div><strong>${totalSessions()}</strong><span>sessions</span></div><div><strong>${state.favorites.length}</strong><span>favorites</span></div><div><strong>${clearedGames()}</strong><span>games cleared</span></div><div><strong>${unlocked}/${achievements.length}</strong><span>achievements</span></div><div><strong>${Math.floor(totalPlaySeconds()/60)}</strong><span>play minutes</span></div><div><strong>${Math.floor(longestSession()/60)}m</strong><span>longest session</span></div><div><strong>${esc(topPlayGenre())}</strong><span>top play genre</span></div>`; renderChallenges(); }
  function recommendationScore(g){ let score=g.basePopularity;const seeds=[...state.recent.slice(0,5),...state.favorites].map(id=>games.find(x=>x.id===id)).filter(Boolean);for(const s of seeds)score+=g.genres.filter(x=>s.genres.includes(x)).length*12;if(state.ratings[g.id])score+=state.ratings[g.id]*4;if(state.plays[g.id])score-=Math.min(15,state.plays[g.id]*2);if(isNew(g))score+=5;return score; }
  function renderRecommendations(){ let list=[...games].sort((a,b)=>recommendationScore(b)-recommendationScore(a));const unplayed=list.filter(g=>!state.plays[g.id]);if(unplayed.length>=3)list=[...unplayed,...list.filter(g=>state.plays[g.id])];list=list.slice(0,3);$('#recommendationGrid').innerHTML=list.map(g=>gameCard(g)).join('');$('#recommendationNote').textContent=uniquePlays()?`Based on ${uniquePlays()} games you have tried, favorites, ratings, and scores.`:'Start playing to personalize this row.';wireFavorites(); }
  const featured=games.find(g=>g.featured)||games[0]; if(featured){$('#heroTitle').textContent=featured.title;$('#heroDescription').textContent=featured.description;$('#heroPlay').href=`game.html?id=${encodeURIComponent(featured.id)}`;$('#heroArt').style.backgroundImage=`linear-gradient(135deg,rgba(7,11,23,.1),rgba(7,11,23,.75)),url('${featured.cover}')`;}
  $('#gameCount').textContent=games.length; $('#genreCount').textContent=new Set(games.flatMap(g=>g.genres)).size;
  const surprise=$('#surprisePlay'); if(surprise) surprise.addEventListener('click',()=>{const unplayed=games.filter(g=>!state.plays[g.id]),pool=unplayed.length?unplayed:games;if(pool.length)location.href=`game.html?id=${encodeURIComponent(pool[Math.floor(Math.random()*pool.length)].id)}`;});
  $('#searchInput').addEventListener('input',e=>{state.query=e.target.value;renderLibrary();}); $('#inputFilter').addEventListener('change',e=>{state.input=e.target.value;renderLibrary();}); if($('#modeFilter'))$('#modeFilter').addEventListener('change',e=>{state.mode=e.target.value;renderLibrary();}); if($('#statusFilter'))$('#statusFilter').addEventListener('change',e=>{state.status=e.target.value;renderLibrary();}); if($('#collectionFilter'))$('#collectionFilter').addEventListener('change',e=>{state.collection=e.target.value;renderLibrary();}); $('#sortSelect').addEventListener('change',e=>{state.sort=e.target.value;renderLibrary();}); $('#profileButton').addEventListener('click',()=>$('#profileDialog').showModal());
  $('#reducedMotion').checked=!!state.prefs.reducedMotion; $('#mutePreference').checked=!!state.prefs.muted; if(!Number.isFinite(Number(state.prefs.volume)))state.prefs.volume=.7; if(!Number.isFinite(Number(state.prefs.textScale)))state.prefs.textScale=1; if($('#volumePreference'))$('#volumePreference').value=Math.round(Number(state.prefs.volume)*100); if($('#highContrast'))$('#highContrast').checked=!!state.prefs.highContrast; if($('#textScale'))$('#textScale').value=Math.round(Number(state.prefs.textScale)*100);
  $('#reducedMotion').addEventListener('change',e=>{state.prefs.reducedMotion=e.target.checked;localStorage.setItem('wwg:prefs',JSON.stringify(state.prefs));applyPrefs();});
  $('#mutePreference').addEventListener('change',e=>{state.prefs.muted=e.target.checked;localStorage.setItem('wwg:prefs',JSON.stringify(state.prefs));});
  if($('#volumePreference'))$('#volumePreference').addEventListener('input',e=>{state.prefs.volume=Math.max(0,Math.min(1,Number(e.target.value)/100));localStorage.setItem('wwg:prefs',JSON.stringify(state.prefs));}); if($('#highContrast'))$('#highContrast').addEventListener('change',e=>{state.prefs.highContrast=e.target.checked;localStorage.setItem('wwg:prefs',JSON.stringify(state.prefs));applyPrefs();}); if($('#textScale'))$('#textScale').addEventListener('input',e=>{state.prefs.textScale=Math.max(.9,Math.min(1.25,Number(e.target.value)/100));localStorage.setItem('wwg:prefs',JSON.stringify(state.prefs));applyPrefs();});
  let installPrompt=null;const installButton=$('#installButton');addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;if(installButton)installButton.hidden=false});if(installButton)installButton.addEventListener('click',async()=>{if(!installPrompt)return;installPrompt.prompt();try{await installPrompt.userChoice}catch{}installPrompt=null;installButton.hidden=true});addEventListener('appinstalled',()=>{installPrompt=null;if(installButton)installButton.hidden=true});
  const keyChoices=[['KeyW','W'],['KeyA','A'],['KeyS','S'],['KeyD','D'],['KeyI','I'],['KeyJ','J'],['KeyK','K'],['KeyL','L'],['ArrowUp','↑'],['ArrowDown','↓'],['ArrowLeft','←'],['ArrowRight','→'],['Space','Space'],['Enter','Enter'],['ShiftLeft','Left Shift'],['KeyQ','Q'],['KeyE','E'],['KeyF','F'],['KeyC','C'],['KeyX','X'],['KeyZ','Z']],keyDefaults={up:'KeyW',down:'KeyS',left:'KeyA',right:'KeyD',primary:'Space',secondary:'KeyE'};
  function renderKeymap(){document.querySelectorAll('[data-key-action]').forEach(sel=>{const action=sel.dataset.keyAction,current=state.keymap[action]||keyDefaults[action];sel.innerHTML=keyChoices.map(([v,l])=>`<option value="${v}" ${v===current?'selected':''}>${l}</option>`).join('');sel.onchange=()=>{state.keymap[action]=sel.value;localStorage.setItem('wwg:keymap',JSON.stringify(state.keymap));renderPersonal()}});const reset=$('#resetKeymap');if(reset)reset.onclick=()=>{state.keymap={};localStorage.removeItem('wwg:keymap');renderKeymap();renderPersonal()}}
  renderKeymap();
  const exportData=$('#exportData');if(exportData)exportData.addEventListener('click',()=>{const data={version:2,exportedAt:new Date().toISOString(),data:{}};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&k.startsWith('wwg:')){const v=localStorage.getItem(k);if(v!=null)data.data[k]=v}}const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='worldwidegames-profile.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});
  const importData=$('#importData'),importFile=$('#importFile');if(importData&&importFile){importData.addEventListener('click',()=>importFile.click());importFile.addEventListener('change',async()=>{const f=importFile.files&&importFile.files[0];if(!f)return;try{const obj=JSON.parse(await f.text());if(!obj||typeof obj.data!=='object')throw new Error('Invalid profile');for(const [k,v] of Object.entries(obj.data))if(k.startsWith('wwg:')&&typeof v==='string')localStorage.setItem(k,v);location.reload()}catch{importData.textContent='Import failed';setTimeout(()=>importData.textContent='Import profile',1400)}})};
  addEventListener('keydown',e=>{if(e.key==='/'&&!/input|select|textarea/i.test(document.activeElement?.tagName||'')){e.preventDefault();$('#searchInput')?.focus()}if(e.code==='KeyP'&&!/input|select|textarea/i.test(document.activeElement?.tagName||'')){$('#profileButton')?.click()}});
  $('#clearData').addEventListener('click',()=>{for(let i=localStorage.length-1;i>=0;i--){const k=localStorage.key(i);if(k&&k.startsWith('wwg:'))localStorage.removeItem(k)}location.reload();});
  renderChips(); renderLibrary(); renderPersonal(); renderRecommendations(); renderChallenges(); renderWeekly(); if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js').catch(()=>{});
})();
