window.WWG_GAMES = [
  {
    id: 'driftglass-links', title: 'Driftglass Links', tagline: 'Read the bank. Trust the roll.',
    description: 'A six-hole precision golf and physics game with drag-to-shoot aiming, ricochet walls, sand, water hazards, gamepad support, and lower-is-better stroke scoring.',
    genres: ['Golf', 'Sports', 'Physics', 'Precision'], added: '2026-09-30', featured: true, basePopularity: 188,
    cover: 'covers/driftglass-links.svg', path: 'games/driftglass-links/index.html', accent: '#5eead4',
    scoreMeta: { unit: 'strokes', direction: 'low', label: 'Course strokes' },
    controls: ['Drag from the ball to aim and set shot power', 'Arrow Left / Right adjusts aim and Up / Down adjusts power', 'Space takes the shot', 'Gamepad left stick aims, triggers change power, and A shoots', 'Touch and pointer play supported', 'R restarts the course', 'Lower stroke totals are better']
  },
  {
    id: 'tideglass-surveyor', title: 'Tideglass Surveyor', tagline: 'Three lighthouses. One hidden coordinate.',
    description: 'A six-chart cartography logic game. Triangulate hidden waymarks from three Manhattan-distance lighthouse readings, manage a four-probe budget, and seal the atlas efficiently.',
    genres: ['Cartography', 'Logic', 'Puzzle', 'Exploration'], added: '2026-09-30', featured: false, basePopularity: 178,
    cover: 'covers/tideglass-surveyor.svg', path: 'games/tideglass-surveyor/index.html', accent: '#7dd3fc',
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Survey score' },
    controls: ['Click or tap any grid sector to move the survey cursor', 'Arrow keys move the cursor one sector', 'Enter / Space probes the selected sector', 'Use all three lighthouse distance readings to triangulate the hidden waymark', 'R resets the current chart']
  },
  {
    id: 'spanwright', title: 'Spanwright', tagline: 'Build the load path. Prove the span.',
    description: 'A five-blueprint construction and engineering puzzle about budgeting beams, creating load-bearing triangles, connecting banks, and certifying each structure with a moving convoy test.',
    genres: ['Construction', 'Engineering', 'Physics', 'Puzzle'], added: '2026-09-30', featured: false, basePopularity: 181,
    cover: 'covers/spanwright.svg', path: 'games/spanwright/index.html', accent: '#2dd4bf',
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Engineering score' },
    controls: ['Tap or click one joint and then another to place a beam', 'T or Space tests the current span', 'Backspace removes the last beam', 'R resets the blueprint', 'Build connected, well-braced structures without exceeding the budget']
  },
  {
    id: 'lantern-line', title: 'Lantern Line', tagline: 'Smooth stops. Quiet streets. Zero excuses.',
    description: 'A city-loop vehicle simulation about throttle, braking, passenger comfort, schedule discipline, and six precise station stops. Finish the route with the lowest total service delay.',
    genres: ['Vehicle Simulation', 'Transit', 'Logistics', 'Simulation'], added: '2026-09-30', featured: false, basePopularity: 174,
    cover: 'covers/lantern-line.svg', path: 'games/lantern-line/index.html', accent: '#fb7185', remappable: true,
    scoreMeta: { unit: 'sec', direction: 'low', label: 'Service delay' },
    controls: ['Remappable Up accelerates and Down brakes', 'Primary / Space opens doors when stopped at a platform', 'R restarts the shift', 'Gamepad triggers + A supported', 'Touch throttle, brake, and doors controls on mobile', 'Lower service-delay scores are better']
  },
  {
    id: 'frostline-rescue', title: 'Frostline Rescue', tagline: 'Contain the fire. Bring everyone home.',
    description: 'A real-time emergency rescue game with spreading fire, stranded residents, water management, a safe-zone escort loop, procedural audio, touch controls, gamepad support, and remappable keyboard movement.',
    genres: ['Rescue', 'Emergency', 'Action', 'Strategy'], added: '2026-09-30', featured: false, basePopularity: 171,
    cover: 'covers/frostline-rescue.svg', path: 'games/frostline-rescue/index.html', accent: '#22d3ee', remappable: true,
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Rescue score' },
    controls: ['Move with remappable directional keys or Arrow keys before customization', 'Primary sprays water at nearby fire', 'Secondary / Enter escorts a nearby resident or secures them at the safe zone', 'Refill water near the blue hydrant', 'Gamepad left stick + A/B supported', 'Touch controls on mobile']
  },
  {
    id: 'signal-choir', title: 'Signal Choir', tagline: 'Hear it. See it. Return the pattern.',
    description: 'A six-round audiovisual memory game with five tonal channels, escalating sequences, replay penalties, streak scoring, three lives, and a complete visual mode for muted play.',
    genres: ['Memory', 'Music', 'Puzzle', 'Relaxing'], added: '2026-09-30', featured: false, basePopularity: 163,
    cover: 'covers/signal-choir.svg', path: 'games/signal-choir/index.html', accent: '#a78bfa',
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Memory score' },
    controls: ['Keys 1-5 repeat the five signal channels', 'Tap or click the five pads on touch/pointer devices', 'Replay Signal repeats the current pattern for a score penalty', 'R restarts the choir']
  },
  {
    id: 'terrace-keeper', title: 'Terrace Keeper', tagline: 'Plant carefully. Let the weather work.',
    description: 'A twelve-day farming and management simulation. Plant three crop types, water terraces, harvest for profit, react to frost and rain, and invest in a cistern or windglass to fulfill the seasonal contract.',
    genres: ['Farming', 'Agriculture', 'Management', 'Relaxing'], added: '2026-09-30', featured: false, basePopularity: 158,
    cover: 'covers/terrace-keeper.svg', path: 'games/terrace-keeper/index.html', accent: '#86efac',
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Terrace score' },
    controls: ['Tap or click a seed type, then an empty terrace to plant', 'Tap planted crops to water them or harvest when ready', 'End Day advances crop growth and weather', 'Optional cistern and windglass upgrades change the season economy']
  },
  {
    id: 'chronofold-courier', title: 'Chronofold Courier', tagline: 'Cooperate with the route you already took.',
    description: 'A five-fold time-loop puzzle where every sealed route becomes an echo that repeats your moves. Coordinate past versions of yourself across pressure plates, walls, and phase-locked exits.',
    genres: ['Time Loop', 'Puzzle', 'Strategy', 'Experimental'], added: '2026-09-30', featured: false, basePopularity: 166,
    cover: 'covers/chronofold-courier.svg', path: 'games/chronofold-courier/index.html', accent: '#c4b5fd', remappable: true,
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Archive score' },
    controls: ['WASD / Arrow keys move one grid step', 'Space seals the current route into a replaying echo', 'X / Period waits one step for synchronization', 'R restarts the full archive', 'Touch direction, wait, and loop controls on mobile']
  },
  {
    id: 'hearthline-kitchen', title: 'Hearthline Kitchen', tagline: 'Read the rail. Hit the heat. Keep service moving.',
    description: 'A seventy-five second cooking and time-management rush. Assemble four recipes, stop the heat meter at the right moment, protect your combo, and serve as many accurate plates as possible.',
    genres: ['Cooking', 'Time Management', 'Management', 'Arcade'], added: '2026-09-30', featured: false, basePopularity: 157,
    cover: 'covers/hearthline-kitchen.svg', path: 'games/hearthline-kitchen/index.html', accent: '#fb923c',
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Service score' },
    controls: ['Keys 1-6 or touch ingredient stations add ingredients', 'C cooks the prepared bowl', 'Enter serves the plate', 'X / Backspace clears the bowl', 'R restarts after service closes']
  },
  {
    id: 'spectra-safari', title: 'Spectra Safari', tagline: 'Track the wild. Frame the moment.',
    description: 'A relaxing wildlife-photography expedition with six species, rarity scoring, framing and distance bonuses, twelve shots of film, roaming creatures, procedural audio, touch controls, and gamepad support.',
    genres: ['Photography', 'Nature', 'Exploration', 'Relaxing'], added: '2026-09-30', featured: false, basePopularity: 153,
    cover: 'covers/spectra-safari.svg', path: 'games/spectra-safari/index.html', accent: '#86efac',
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Survey score' },
    controls: ['WASD / Arrow keys pan the field camera', 'Space takes a photograph', 'Frame wildlife near the center reticle for stronger scores', 'Gamepad left stick + A supported', 'Touch movement and PHOTO controls on mobile']
  },
  {
    id: 'ashfall-caravan', title: 'Ashfall Caravan', tagline: 'Carry the people. Spend the future carefully.',
    description: 'A branching narrative-management journey across eight ashland crossings with persistent Chronicle progression. Complete journeys to earn caravan traits, alter later routes, and archive distinct endings while balancing supplies, morale, heat, and crew.',
    genres: ['Narrative', 'Adventure', 'Management', 'Interactive Fiction'], added: '2026-09-30', featured: false, basePopularity: 158,
    cover: 'covers/ashfall-caravan.svg', path: 'games/ashfall-caravan/index.html', accent: '#fb7185',
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Journey score' },
    controls: ['Choose between two story decisions each day', 'Keys 1 / 2 choose decisions', 'Tap or click choice cards on touch devices', 'Completed journeys unlock a persistent caravan trait and route variant', 'R restarts after the journey ends']
  },
  {
    id: 'twinforge-expedition', title: 'Twinforge Expedition', tagline: 'Two pilots. One forge. Three sectors.',
    description: 'A same-device cooperative expedition for two players. Gather shared ore and crystal, evade moving hazards, manage one energy reserve, and dock together to build three forge relays.',
    genres: ['Co-op', 'Multiplayer', 'Exploration', 'Survival'], added: '2026-09-30', featured: false, basePopularity: 151,
    cover: 'covers/twinforge-expedition.svg', path: 'games/twinforge-expedition/index.html', accent: '#67e8f9',
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Team score' },
    controls: ['Player 1: WASD + F to build', 'Player 2: Arrow keys + / to build', 'Dual touch controls are available on mobile', 'Two gamepads supported when connected', 'Both players must dock and hold build together']
  },
  {
    id: 'mothlight-museum', title: 'Mothlight Museum', tagline: 'Find what the archive forgot.',
    description: 'A three-room hidden-object investigation with fifteen hand-placed exhibits, hint penalties, room-clear bonuses, touch/pointer play, and a final case score based on speed and observation.',
    genres: ['Hidden Object', 'Mystery', 'Puzzle', 'Observation'], added: '2026-09-30', featured: false, basePopularity: 146,
    cover: 'covers/mothlight-museum.svg', path: 'games/mothlight-museum/index.html', accent: '#c4b5fd',
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Case score' },
    controls: ['Click or tap listed exhibits in each gallery', 'H or the Hint button reveals one target for a score penalty', 'R restarts the investigation']
  },
  {
    id: 'windward-cargo',
    title: 'Windward Cargo',
    tagline: 'Read the sky. Protect the payload.',
    description: 'A momentum-based flight and delivery game with shifting wind fields, fuel management, cargo integrity, gentle landing requirements, four escalating routes, procedural audio, touch controls, and gamepad support.',
    genres: ['Flight', 'Delivery', 'Physics', 'Arcade'],
    added: '2026-09-30', featured: false, basePopularity: 142,
    cover: 'covers/windward-cargo.svg', path: 'games/windward-cargo/index.html', accent: '#38bdf8',
    controls: ['W / Arrow Up applies thrust', 'A / D or Left / Right changes pitch', 'Space boosts at higher fuel cost', 'Fly through cyan pickup rings and land gently in gold delivery rings', 'Touch controls on mobile', 'Gamepad left stick + A/B supported'], scoreMeta:{unit:'pts',direction:'high',label:'flight score'}
  },
  {
    id: 'cipher-court',
    title: 'Cipher Court',
    tagline: 'Every clue narrows the room.',
    description: 'A four-case deduction game. Compare suspect traits against evidence, reveal extra clues at a score cost, avoid false accusations, and close the full docket with the strongest possible reasoning score.',
    genres: ['Deduction', 'Mystery', 'Logic', 'Puzzle'],
    added: '2026-09-30', featured: false, basePopularity: 136,
    cover: 'covers/cipher-court.svg', path: 'games/cipher-court/index.html', accent: '#c084fc',
    controls: ['Click or tap a suspect to select them', 'Accuse selected suspect when the evidence fits', 'Reveal another clue costs score', 'Enter accuses / Space reveals another clue', 'R restarts the docket'], scoreMeta:{unit:'pts',direction:'high',label:'deduction score'}
  },
  {
    id: 'moonwake-angler',
    title: 'Moonwake Angler',
    tagline: 'Cast by moonlight. Read the tension.',
    description: 'A relaxed fishing game with bite timing, line-tension management, five fish species, species values, a 90-second night haul, procedural audio, touch input, and gamepad support.',
    genres: ['Fishing', 'Relaxing', 'Simulation'],
    added: '2026-09-30', featured: false, basePopularity: 132,
    cover: 'covers/moonwake-angler.svg', path: 'games/moonwake-angler/index.html', accent: '#93c5fd',
    controls: ['Space / CAST throws the line', 'Reel when the float flashes', 'Hold and release REEL to keep tension below the red zone', 'R restarts the night haul', 'Touch controls on mobile', 'Gamepad A supported'], scoreMeta:{unit:'pts',direction:'high',label:'haul score'}
  },
  {
    id: 'deepwater-signal', title: 'Deepwater Signal', tagline: 'Ping the dark. Wake nothing.',
    description: 'A sonar-stealth undersea expedition. Synchronize five drowned relays, manage battery and hull, evade sound-hunting predators, and return to the surface gate with the strongest survey score.',
    genres: ['Underwater', 'Stealth', 'Exploration', 'Simulation'], added: '2026-09-30', featured: false, basePopularity: 132,
    cover: 'covers/deepwater-signal.svg', path: 'games/deepwater-signal/index.html', accent: '#67e8f9',
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Mission score' },
    controls: ['WASD / Arrow keys pilot the submersible', 'Space fires a sonar pulse', 'E scans a nearby relay or exits at the surface gate', 'Gamepad left stick + A ping / B scan supported', 'Touch movement, ping, and scan controls on mobile', 'R restarts the mission']
  },
  {
    id: 'emberdeck-pilgrim', title: 'Emberdeck Pilgrim', tagline: 'Carry a living deck through three furnace gates.',
    description: 'A branching deckbuilding roguelike with readable enemy intent, energy, block, healing, route-specific encounters, Legacy-gated boons, card rewards, and score pressure from health and run time.',
    genres: ['Deckbuilder', 'Card', 'Roguelike', 'Strategy'], added: '2026-09-30', featured: false, basePopularity: 129,
    cover: 'covers/emberdeck-pilgrim.svg', path: 'games/emberdeck-pilgrim/index.html', accent: '#fb923c',
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Pilgrimage score' },
    controls: ['Tap cards or use keys 1-5 to play them', 'E or Space ends the current turn', 'Read enemy intent before spending energy', 'Choose one reward card after the first two victories', 'R restarts the pilgrimage']
  },
  {
    id: 'command-bloom', title: 'Command Bloom', tagline: 'Program the garden one instruction at a time.',
    description: 'A six-stage programming logic puzzle about building short command queues, rotating a drone, navigating root walls, pulsing energy cores, and reaching each green gate efficiently.',
    genres: ['Programming', 'Logic', 'Puzzle'], added: '2026-09-30', featured: false, basePopularity: 127,
    cover: 'covers/command-bloom.svg', path: 'games/command-bloom/index.html', accent: '#86efac',
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Program score' },
    controls: ['F/L/R/P add Forward, Left, Right, and Pulse commands', 'Enter runs the queued program', 'Backspace removes the last instruction', 'Tap/click controls support touch and pointer play', 'Escape resets the current stage or restarts after completion']
  },
  {
    id: 'railspire-dispatch',
    title: 'Railspire Dispatch',
    tagline: 'Four switches. One network. No collisions.',
    description: 'A fast logistics-routing game about reading rail flow, toggling switches, matching colored trains to depots, and keeping a busy elevated network collision-free.',
    genres: ['Logistics', 'Strategy', 'Puzzle'],
    added: '2026-09-30', featured: false, basePopularity: 126,
    cover: 'covers/railspire-dispatch.svg', path: 'games/railspire-dispatch/index.html', accent: '#a7f3d0',
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Dispatch score' },
    controls: ['Keys 1-4 toggle the four rail switches', 'Tap amber switches or on-screen switch buttons', 'Route each colored train to its matching depot', 'Avoid three strikes from wrong depots or collisions', 'R restarts the shift']
  },
  {
    id: 'glyphsmith', title: 'Glyphsmith', tagline: 'Forge words before the archive cools.',
    description: 'A sixty-second word-forging sprint. Type or tap runes to recreate the target word, build combo chains, and keep the archive alive under a fast countdown.',
    genres: ['Word', 'Typing', 'Puzzle'], added: '2026-09-30', featured: false, basePopularity: 123,
    cover: 'covers/glyphsmith.svg', path: 'games/glyphsmith/index.html', accent: '#e879f9',
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Forge score' },
    controls: ['Type letters on a keyboard or tap the rune bank', 'Enter forges the current word', 'Backspace removes the last rune', 'Escape clears the entry', 'R restarts after the archive closes']
  },
  {
    id: 'solar-loom', title: 'Solar Loom', tagline: 'Build a stable little universe.',
    description: 'An experimental orbital sandbox about placing different world types, balancing gravitational mass, maximizing habitability, and shepherding a tiny solar system through eight epochs.',
    genres: ['Sandbox', 'Experimental', 'Simulation', 'Strategy'], added: '2026-09-30', featured: false, basePopularity: 121,
    cover: 'covers/solar-loom.svg', path: 'games/solar-loom/index.html', accent: '#93c5fd',
    scoreMeta: { unit: 'pts', direction: 'high', label: 'System score' },
    controls: ['Tap or click an orbit to place the selected world', 'Buttons or keys 1-4 choose world types', 'Space advances an epoch', 'R restarts the system', 'Keep stability above 25 through eight epochs']
  },
  {
    id: 'atlas-below',
    title: 'Atlas Below',
    tagline: 'Mine the dark. Build the signal. Find the way home.',
    description: 'A procedural cave expedition where rank changes the cave itself: route width, chamber density, crystal abundance, toxic gas, and survey-cache frequency evolve as you earn Rebreather, Surveyor, and Deep Cartographer status. Mine, craft a beacon, and extract before your air runs out.',
    genres: ['Exploration', 'Survival', 'Crafting'],
    added: '2026-09-30',
    featured: false,
    basePopularity: 120,
    cover: 'covers/atlas-below.svg',
    path: 'games/atlas-below/index.html',
    accent: '#7dd3fc', remappable: true,
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Expedition score' },
    controls: ['WASD / Arrow keys move', 'Space mines an adjacent resource vein', 'C crafts the extraction beacon after collecting 6 ore and 2 crystals', 'R restarts the expedition', 'Gamepad left stick + A mine / B craft supported', 'Touch controls on mobile', 'Successful extractions unlock rank-shaped cave generation, oxygen, a signal compass, survey caches, and gas protection']
  },
  {
    id: 'aetherstead-colony',
    title: 'Aetherstead Colony',
    tagline: 'Sixteen turns to make a city float.',
    description: 'A turn-based city-building simulation about housing, food, water, power, research, morale, upgrades, and population growth across a sixteen-turn colony charter.',
    genres: ['City Builder', 'Colony', 'Simulation', 'Strategy'],
    added: '2026-09-30',
    featured: false,
    basePopularity: 118,
    cover: 'covers/aetherstead-colony.svg',
    path: 'games/aetherstead-colony/index.html',
    accent: '#93c5fd',
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Colony score' },
    controls: ['Tap or click an open platform to construct the selected building', 'Tap an existing matching building to upgrade it', '1-6 select building types', 'Space advances one turn', 'R restarts the colony']
  },
  {
    id: 'prism-duel',
    title: 'Prism Duel',
    tagline: 'Bank the shot. Read the angle. Beat the room.',
    description: 'A ricochet arena for solo or same-device competitive play. Duel a tracking AI or a second local pilot, bank shots around prism cover, and win a first-to-five skiff battle.',
    genres: ['Multiplayer', 'Competitive', 'Arena', 'Physics'],
    added: '2026-09-30',
    featured: false,
    basePopularity: 124,
    cover: 'covers/prism-duel.svg',
    path: 'games/prism-duel/index.html',
    accent: '#c4b5fd', modes: ['Solo', 'Local Multiplayer'],
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Duel score' },
    controls: ['Mode button or M toggles two-player and VS AI play', 'Player 1: WASD turns/drives, F fires', 'Player 2: Arrow keys turn/drive, / fires in local multiplayer', 'Shots ricochet from walls and prism blocks', 'First pilot to 5 points wins', 'Two gamepads supported in local multiplayer', 'Dual touch controls are available on screen']
  },
  {
    id: 'crownline-tactics',
    title: 'Crownline Tactics',
    tagline: 'Three operatives. Six turns ahead.',
    description: 'A turn-based squad tactics game built around positioning, cover, relay control, limited action points, and readable enemy intent. Capture all three crown relays or eliminate the opposing wardens before the twelfth round.',
    genres: ['Tactical', 'Strategy', 'Turn-Based'],
    added: '2026-09-30',
    featured: false,
    basePopularity: 114,
    cover: 'covers/crownline-tactics.svg',
    path: 'games/crownline-tactics/index.html',
    accent: '#facc15',
    controls: ['Click or tap one of your operatives to select it', 'Select a neighboring tile to move for 1 AP', 'Select an enemy within range 2 to attack for 1 AP', 'Each operative has 2 AP each round', 'End Turn resolves the wardens and refreshes your squad']
  },
  {
    id: 'echo-bazaar',
    title: 'Echo Bazaar',
    tagline: 'Read the market before the market reads you.',
    description: 'A twelve-day trading simulation about cargo space, shifting demand, rumor events, and compounding risk. Buy low, sell high, survive market shocks, and finish with the strongest net worth.',
    genres: ['Economy', 'Simulation', 'Management', 'Strategy'],
    added: '2026-09-30',
    featured: false,
    basePopularity: 112,
    cover: 'covers/echo-bazaar.svg',
    path: 'games/echo-bazaar/index.html',
    accent: '#fb7185',
    controls: ['Tap or click a commodity row to select it', 'Buy and Sell trade one unit at the current price', 'Cargo capacity is limited to 12 units', 'Advance Day refreshes prices and market rumors', 'Finish day 12 with the highest possible net worth']
  },
  {
    id: 'lumen-relay',
    title: 'Lumen Relay',
    tagline: 'Turn the mirrors. Carry the light.',
    description: 'A six-stage laser-routing logic puzzle. Rotate mirrors to bend a live beam through every crystal and into the receiver while avoiding absorbers and minimizing total turns.',
    genres: ['Logic', 'Puzzle', 'Board'],
    added: '2026-09-30',
    featured: false,
    basePopularity: 111,
    cover: 'covers/lumen-relay.svg',
    path: 'games/lumen-relay/index.html',
    accent: '#fde68a',
    controls: ['Click or tap a mirror to rotate it', 'Route the beam through every crystal before the receiver', 'Absorbers stop the beam immediately', 'R restarts the current stage', 'Complete all 6 stages with as few rotations as possible']
  },
  {
    id: 'starweaver-drift',
    title: 'Starweaver Drift',
    tagline: 'Chart the quiet between worlds.',
    description: 'A non-combat space exploration run about fuel, momentum, gravitational anomalies, six survey beacons, and returning your completed constellation to the relay with as much data and hull integrity as possible.',
    genres: ['Space', 'Exploration', 'Simulation'],
    added: '2026-09-30',
    featured: false,
    basePopularity: 110,
    cover: 'covers/starweaver-drift.svg',
    path: 'games/starweaver-drift/index.html',
    accent: '#67e8f9',
    controls: ['WASD / Arrow keys steer', 'Space boosts at extra fuel cost', 'Hold E near a beacon to scan', 'R restarts the survey', 'Gamepad left stick + A/B supported', 'Touch controls on mobile']
  },
  {
    id: 'pulse-archive',
    title: 'Pulse Archive',
    tagline: 'Sync the signal. Preserve the beat.',
    description: 'A four-lane rhythm game built around timing, combo recovery, adaptive scoring, procedural Web Audio pulses, touch controls, keyboard lanes, and gamepad face buttons.',
    genres: ['Rhythm', 'Music', 'Arcade'],
    added: '2026-09-30',
    featured: false,
    basePopularity: 108,
    cover: 'covers/pulse-archive.svg',
    path: 'games/pulse-archive/index.html',
    accent: '#c084fc',
    controls: ['D F J K hit the four lanes', 'Hit notes as they cross the timing line', 'Touch lane buttons on mobile', 'Gamepad face buttons supported', 'Mute preference disables procedural tones']
  },
  {
    id: 'verdant-circuit',
    title: 'Verdant Circuit',
    tagline: 'Design an ecosystem that can survive itself.',
    description: 'A turn-based ecology strategy game. Spend limited energy placing water, seeds, and mycelium, then simulate fourteen turns where neighboring species support or starve one another. Diversity and healthy connections drive the final score.',
    genres: ['Ecology', 'Strategy', 'Simulation', 'Board'],
    added: '2026-09-30',
    featured: false,
    basePopularity: 106,
    cover: 'covers/verdant-circuit.svg',
    path: 'games/verdant-circuit/index.html',
    accent: '#86efac',
    controls: ['Click or tap cells to place the selected organism', '1 / 2 / 3 switch Water, Seed, Mycelium', 'Space advances the ecosystem one turn', 'Plan for diversity and neighboring support', 'Advance starts a new run after turn 14']
  },
  {
    id: 'quiet-protocol',
    title: 'Quiet Protocol',
    tagline: 'Read the room. Cut the signal. Leave unseen.',
    description: 'A compact stealth-puzzle infiltration game. Slip through vision cones, disable security relays, use short-lived signal cloaks, and extract before the facility reaches full alert.',
    genres: ['Stealth', 'Puzzle', 'Action'],
    added: '2026-09-30',
    featured: false,
    basePopularity: 104,
    cover: 'covers/quiet-protocol.svg',
    path: 'games/quiet-protocol/index.html',
    accent: '#5eead4', remappable: true,
    controls: ['WASD / Arrow keys move', 'E hacks nearby relays', 'Space activates a signal cloak when charged', 'Avoid guard vision cones', 'Gamepad left stick + A/B supported']
  },
  {
    id: 'forgeflow',
    title: 'Forgeflow',
    tagline: 'Turn the line. Feed the core. Waste nothing.',
    description: 'An automation-routing puzzle about rotating factory modules to move ore through processors and into the reactor. Build efficient chains, manage heat, and beat each quota before the shift ends.',
    genres: ['Automation', 'Strategy', 'Simulation', 'Puzzle'],
    added: '2026-09-30',
    featured: false,
    basePopularity: 102,
    cover: 'covers/forgeflow.svg',
    path: 'games/forgeflow/index.html',
    accent: '#fb923c',
    controls: ['Click or tap tiles to rotate conveyors', 'Route ore through at least one processor before the reactor', 'Keep jams from overheating the grid', 'R resets the current factory']
  },
  {
    id: 'cloudforge-pinball',
    title: 'Cloudforge Pinball',
    tagline: 'Charge the storm. Keep the sphere alive.',
    description: 'A physics-driven pinball table suspended over a storm forge, with reactive bumpers, combo lanes, multiball charge, keyboard/touch controls, and gamepad-ready flippers.',
    genres: ['Pinball', 'Physics', 'Arcade'],
    added: '2026-09-30',
    featured: false,
    basePopularity: 101,
    cover: 'covers/cloudforge-pinball.svg',
    path: 'games/cloudforge-pinball/index.html',
    accent: '#60a5fa',
    controls: ['A / Left Arrow controls left flipper', 'D / Right Arrow controls right flipper', 'Space launches and nudges', 'Gamepad triggers / A supported', 'Touch buttons on mobile']
  },
  {
    id: 'mosslight-vale',
    title: 'Mosslight Vale',
    tagline: 'A small world with a long memory.',
    description: 'A growing top-down exploration RPG spanning five linked regions from Mosslight Village through Silverfen, Sunfall Reach, and Moonroot Hollow, with NPC quest arcs, real-time combat, collectible relics, boss progression, a field-pack inventory, five gear tiers, local saving, four-stop fast travel, and persistent world state.',
    genres: ['RPG', 'Adventure', 'Exploration'],
    added: '2026-09-30',
    featured: false,
    basePopularity: 100,
    cover: 'covers/mosslight-vale.svg',
    path: 'games/mosslight-vale/index.html',
    accent: '#86efac', remappable: true,
    controls: ['WASD / Arrow keys move', 'Space attacks', 'E interacts / talks / saves', 'Shift dashes', 'H uses a potion', 'F cycles unlocked fast-travel hubs including Moonroot Hollow', 'I opens the field-pack inventory', 'Touch controls on mobile']
  },
  {
    id: 'gravity-foundry',
    title: 'Gravity Foundry',
    tagline: 'Bend the orbit. Build the path.',
    description: 'A physics puzzle about launching a probe through gravitational fields. Sweep every energy core, avoid planetary collisions, and enter the stabilized gate using as few launches as possible.',
    genres: ['Physics', 'Puzzle', 'Simulation'],
    added: '2026-09-30',
    featured: false,
    basePopularity: 98,
    cover: 'covers/gravity-foundry.svg',
    path: 'games/gravity-foundry/index.html',
    accent: '#67e8f9',
    controls: ['Drag backward from the probe to aim', 'Release to launch', 'Collect every core before entering the gate', 'R resets the field', 'Pointer and touch controls supported']
  },
  {
    id: 'hexbound-tactics',
    title: 'Hexbound Tactics',
    tagline: 'Play the lane. Break the citadel.',
    description: 'A compact card-battle tactics game with three contested lanes, an energy economy, a rotating hand, simultaneous combat resolution, and an AI rival that builds its own board each turn.',
    genres: ['Card', 'Strategy', 'Board'],
    added: '2026-09-30',
    featured: false,
    basePopularity: 97,
    cover: 'covers/hexbound-tactics.svg',
    path: 'games/hexbound-tactics/index.html',
    accent: '#c4b5fd',
    controls: ['Select a card from your hand', 'Choose a lane to deploy it', 'Spend up to 4 energy each turn', 'End Turn to resolve combat', 'Touch and mouse supported']
  },
  {
    id: 'harbor-pulse',
    title: 'Harbor Pulse',
    tagline: 'Route the fleet. Protect the harbor.',
    description: 'A real-time harbor-management simulation. Assign color-coded arrivals to matching berths, prevent collisions, keep ships from abandoning the harbor, and build the highest 90-second credit total.',
    genres: ['Simulation', 'Management', 'Arcade'],
    added: '2026-09-30',
    featured: false,
    basePopularity: 96,
    cover: 'covers/harbor-pulse.svg',
    path: 'games/harbor-pulse/index.html',
    accent: '#22d3ee',
    controls: ['Tap or click a ship to select it', 'Tap its matching colored berth to route it', 'Avoid collisions and abandoned arrivals', 'Protect your reputation for 90 seconds']
  },
  {
    id: 'rift-relay',
    title: 'Rift Relay',
    tagline: 'Two players. One orb. Hold the link.',
    description: 'A same-device two-player cooperative arena game. Coordinate two runners, protect the shared relay orb, dodge moving hazards, and carry the charge through eight rotating rifts before the team shield or clock collapses.',
    genres: ['Co-op', 'Multiplayer', 'Arcade'],
    added: '2026-09-30',
    featured: false,
    basePopularity: 96,
    cover: 'covers/rift-relay.svg',
    path: 'games/rift-relay/index.html',
    accent: '#c4b5fd',
    controls: ['Player 1 uses WASD', 'Player 2 uses Arrow keys', 'Touch the orb to carry it', 'Stay close while carrying the shared charge', 'Reach all 8 rifts before time or shield runs out']
  },
  {
    id: 'skyhook-sprint',
    title: 'Skyhook Sprint',
    tagline: 'Run the skyline. Catch the anchor. Never touch the void.',
    description: 'A momentum platformer built around jumps and a quick-release grappling hook. Chain swings between rooftop anchors, collect skyline stars, and race for a faster finish.',
    genres: ['Platformer', 'Action', 'Speedrun'],
    added: '2026-09-29',
    featured: false,
    basePopularity: 95,
    cover: 'covers/skyhook-sprint.svg',
    path: 'games/skyhook-sprint/index.html',
    accent: '#38bdf8', remappable: true,
    controls: ['← / → move', 'Space jumps', 'E attaches/releases the nearest hook', 'R restarts', 'Gamepad left stick + A/B supported', 'Touch controls on mobile']
  },
  {
    id: 'neon-stack',
    title: 'Neon Stack',
    tagline: 'Stack fast. Clear clean. Chase the glow.',
    description: 'A crisp falling-block puzzler with escalating speed, combo scoring, ghost placement, keyboard and touch controls, and instant restarts.',
    genres: ['Puzzle', 'Arcade'],
    added: '2026-09-29',
    featured: false,
    basePopularity: 94,
    cover: 'covers/neon-stack.svg',
    path: 'games/neon-stack/index.html',
    accent: '#8b5cf6',
    controls: ['← / → move', '↓ soft drop', 'Z / X rotate', 'Space hard drop', 'P pause', 'Gamepad D-pad + face buttons supported', 'Touch controls on mobile']
  },
  {
    id: 'circuit-rush',
    title: 'Circuit Rush',
    tagline: 'Three laps. One clean line. Beat your own ghost.',
    description: 'A top-down time-trial racer with momentum steering, off-track slowdown, a pace ghost, touch controls, and persistent best times.',
    genres: ['Racing', 'Arcade', 'Time Trial'],
    added: '2026-09-29',
    featured: false,
    basePopularity: 93,
    cover: 'covers/circuit-rush.svg',
    path: 'games/circuit-rush/index.html',
    accent: '#34d399', remappable: true,
    controls: ['Remappable Up accelerates and Down brakes/reverses', 'Remappable Left / Right steers', 'R restarts', 'Touch controls on mobile', 'Gamepad left stick supported']
  },
  {
    id: 'bastion-bloom',
    title: 'Bastion Bloom',
    tagline: 'Plant the defense. Grow the line. Hold the garden.',
    description: 'A compact tower-defense game where sunlight buys offensive blooms and slowing frost towers. Upgrade your garden between waves and keep the invasion off the final path tile.',
    genres: ['Strategy', 'Tower Defense'],
    added: '2026-09-29',
    featured: false,
    basePopularity: 92,
    cover: 'covers/bastion-bloom.svg',
    path: 'games/bastion-bloom/index.html',
    accent: '#a3e635',
    controls: ['Select Bloom or Frost', 'Click or tap a garden node to build', 'Tap an existing tower to upgrade it', 'Start each wave from the bottom controls']
  },
  {
    id: 'emberfield-survival',
    title: 'Emberfield Survival',
    tagline: 'Move, evolve, and keep the last ember alive.',
    description: 'A survival-arena run with automatic targeting, dash movement, escalating swarms, collectible embers, and mid-run upgrades that reshape your build.',
    genres: ['Survival', 'Action', 'Roguelite'],
    added: '2026-09-29',
    featured: false,
    basePopularity: 91,
    cover: 'covers/emberfield-survival.svg',
    path: 'games/emberfield-survival/index.html',
    accent: '#f97316',
    controls: ['WASD / Arrow keys move', 'Space dashes', 'Weapons automatically target the nearest threat', 'Choose upgrades when you level', 'Gamepad left stick + A dash supported', 'Touch controls on mobile']
  },
  {
    id: 'vector-league',
    title: 'Vector League',
    tagline: 'Ninety seconds. Five goals. Own the angle.',
    description: 'A fast one-on-one neon arena sport against an AI rival. Chase, bump, angle your shots, and score through the opposing gate before the clock expires.',
    genres: ['Sports', 'Competitive', 'Arcade'],
    added: '2026-09-29',
    featured: false,
    basePopularity: 90,
    cover: 'covers/vector-league.svg',
    path: 'games/vector-league/index.html',
    accent: '#22d3ee',
    controls: ['WASD / Arrow keys move', 'Space kicks when near the ball', 'Aim vertical shot angle while moving up/down', 'First to 5 or leader at 90 seconds wins', 'Gamepad left stick + A supported', 'Touch controls on mobile']
  },
  {
    id: 'orbit-breaker',
    title: 'Orbit Breaker',
    tagline: 'Hold the line above a collapsing world.',
    description: 'A fast space-combat arcade game with wave pressure, combo multipliers, screen-wrapping movement, shield pickups, and local high scores.',
    genres: ['Space', 'Shooter', 'Arcade'],
    added: '2026-09-29',
    featured: false,
    basePopularity: 89,
    cover: 'covers/orbit-breaker.svg',
    path: 'games/orbit-breaker/index.html',
    accent: '#22d3ee', remappable: true,
    controls: ['Remappable Left / Right moves the ship', 'Primary fires', 'P pauses', 'Touch buttons on mobile', 'Gamepad left stick + A supported']
  },
  {
    id: 'rune-depths',
    title: 'Rune Depths',
    tagline: 'Find the sigils. Survive the maze. Escape alive.',
    description: 'A compact procedural dungeon run. Explore a fresh maze each game, recover five lost sigils, fight roaming shades, and reach the exit before your health is gone.',
    genres: ['Dungeon', 'Roguelite', 'Adventure'],
    added: '2026-09-29',
    featured: false,
    basePopularity: 87,
    cover: 'covers/rune-depths.svg',
    path: 'games/rune-depths/index.html',
    accent: '#f59e0b',
    controls: ['WASD / Arrow keys move', 'Space attacks nearby enemies', 'R restarts', 'Touch controls on mobile']
  }
];

window.WWG_GAMES.forEach(game => {
  if (!game.scoreMeta) game.scoreMeta = { unit: 'pts', direction: 'high', label: 'Local score' };
});
