window.WWG_GAMES = [
  {id:'ironlight-breach',title:'Ironlight Breach',tagline:'Five sectors. Three weapons. Every secret changes the route.',description:'A retro corridor first-person shooter with five sectors, three weapons, keycard doors, hidden cipher routes, ranged sentries, recovery pickups, and extraction scoring.',objective:'Recover all three breach cores in each sector, survive the sentinel force, and reach extraction. Find optional secrets to open cipher routes and vaults.',genres:['FPS','Action','Shooter','3D','Dungeon'],added:'2026-10-01',updated:'2026-10-02',version:'3.0',featured:false,basePopularity:420,cover:'covers/ironlight-breach.svg',path:'games/ironlight-breach/index.html',accent:'#f59e0b',remappable:true,scoreMeta:{unit:'pts',direction:'high',label:'Breach score'},controls:['Arrow keys or WASD always move and strafe; custom remaps also remain valid','Primary fires the current weapon; 1 / 2 / 3 or V cycles rifle, scattergun, and Arc Lance','Secondary sprints while held','Mouse movement or Q / E turns the view','Keycards automatically open red sealed doors; accumulated secrets unlock cyan cipher routes','Arc Lance pierces up to three aligned targets and disrupts drones or ranged sentries','Find optional cipher vaults, secret caches, ammo, med gel, and weapon pickups across five sectors','Ranged sentries fire visible bolts that can be broken by cover and corridor geometry','Touch movement, fire, sprint, and weapon switching supported','Recover three breach cores and reach extraction in each sector','R restarts from the current sector checkpoint without farming prior-sector score']},
  {id:'verdant-echoes',title:'Verdant Echoes',tagline:'Two bosses. One buried kingdom. A grove that remembers.',description:'A long-form top-down fantasy action-adventure spanning Echo Grove and the buried Rootvault, with sword combat, dashes, bombs, secrets, persistent equipment, quests, and two major bosses.',objective:'Explore both regions, find the three Moon Seeds, defeat the Hollow Stag, forge Moonsteel, then defeat the Thorn Regent to restore the grove.',genres:['Action Adventure','Fantasy','Exploration','RPG','Dungeon','Boss'],added:'2026-10-01',updated:'2026-10-02',version:'2.0',featured:false,basePopularity:372,cover:'covers/verdant-echoes.svg',path:'games/verdant-echoes/index.html',accent:'#86efac',remappable:true,scoreMeta:{unit:'pts',direction:'high',label:'Grove score'},controls:['Remappable directions explore Echo Grove and the Rootvault','Primary swings the equipped blade; Moonsteel deals double sword damage','Secondary performs an invulnerable dash','B places a bomb to break cracked stone and damage enemies','F interacts with Rootkeeper Mira, the Rootvault shrine, and dungeon exits','Find three Moon Seeds, defeat the Hollow Stag, and forge Moonsteel before the Thorn Regent finale','Barkguard Charm raises maximum hearts; campaign progress autosaves locally','Touch movement, sword, dash, bomb, and interact controls supported','R clears the active adventure save and restarts']},
  {id:'ashen-covenant',title:'Ashen Covenant',tagline:'Cross the ash. Forge your weapon. Return for what death took.',description:'A long-form stamina action RPG pilgrimage across three dangerous routes with weapon builds, shrines, recoverable death marks, persistent upgrades, and escalating Covenant Lord fights.',objective:'Bind all three Ember Sigils and defeat every path foe to open each Lord arena. Defeat all three Covenant Lords while preserving and upgrading your Ash-powered build.',genres:['Soulslike','Action RPG','Boss Rush','Fantasy','Combat'],added:'2026-10-01',updated:'2026-10-02',version:'2.0',featured:false,basePopularity:395,cover:'covers/ashen-covenant.svg',path:'games/ashen-covenant/index.html',accent:'#fb7185',remappable:true,scoreMeta:{unit:'pts',direction:'high',label:'Covenant score'},controls:['Remappable directions traverse each ash path and Lord arena','Primary performs the current weapon light attack; Q switches Emberblade and Ash Pike','Secondary dodges with brief invulnerability; H performs a weapon-specific heavy attack','F interacts with Ember Sigils, Lord gates, and shrines or drinks a flask when no interaction is nearby','Bind three Ember Sigils and defeat every path foe to unlock each Covenant Lord','Spend Ash at Ember Shrines to forge the current weapon or bind additional maximum Vigor','Hounds, Pilgrims, and ranged Ash Archers pressure each traversal path before the boss','Recover lost Ash by leaving and deliberately revisiting the death mark; path progress and upgrades persist','Touch movement, light attack, and dodge controls supported; panel buttons expose switch/interact/heavy/restart']},
    {id:'astral-menagerie',title:'Astral Menagerie',tagline:'Complete the Atlas. Study the habitats. Master the constellation.',description:'A three-habitat creature-collection RPG with fifteen original Astral species, four-creature parties, elemental techniques, trainer gauntlets, field studies, Wardens, and post-Atlas mastery trials.',objective:'In each habitat, win two wild battles, defeat the marked trainer, then defeat the Warden. Clear all three habitats to complete the Atlas; afterward, master trainer rematches and Ascendant Wardens.',genres:['Creature Collection','RPG','Turn-Based','Exploration','Adventure'],added:'2026-10-01',updated:'2026-10-02',version:'3.1',featured:false,basePopularity:438,cover:'covers/astral-menagerie.svg',path:'games/astral-menagerie/index.html',accent:'#93c5fd',remappable:true,scoreMeta:{unit:'pts',direction:'high',label:'Atlas score'},controls:['Arrow keys or WASD always explore each habitat; custom remaps also remain valid','Primary attacks during battle; Secondary throws a capture capsule at weakened wild Astrals','F uses the active Astral technique: Scorch, Snare, Mend, Static, or Guard','Q switches to another healthy party member during battle','Complete two wild field wins and defeat the habitat trainer to unlock its Warden','E is contextual: study the nearby field node outside battle; capture weakened wild Astrals in battle','T opens Atlas Mastery Trials after the first clear: trainer rematches unlock Ascendant Wardens','Captured Astrals fill the four-creature party first, then move to reserve for later swaps','Fifteen species, three trainer gauntlets, three habitat quests, three Wardens, and post-Atlas mastery form the full campaign','Touch movement, attack, capture, switch, and technique controls supported','Active expedition and lifetime Atlas/mastery records persist locally; R clears the active expedition save']},
  {id:'polyforge-studio',title:'Polyforge Studio',tagline:'Group the build. Transform the assembly. Share the scene.',description:'A full browser 3D design studio with grouped assemblies, transform gizmos, materials, grid snapping, portable scene-code sharing, undo/redo, and persistent scenes.',objective:'Build the requested 3D structures and complete all seven certification blueprints using placement, grouping, material, move, rotate, and scale tools.',genres:['3D Design','Sandbox','Creative','Simulation','Puzzle'],added:'2026-10-01',updated:'2026-10-02',version:'3.0',featured:false,basePopularity:405,cover:'covers/polyforge-studio.svg',path:'games/polyforge-studio/index.html',accent:'#c4b5fd',remappable:true,scoreMeta:{unit:'pts',direction:'high',label:'Studio score'},controls:['Use toolbar buttons to place Cube, Pillar, or Orb primitives','Click an object to select it; Shift-click adds/removes objects and clicking a grouped object selects its assembly','1 / 2 / 3 switches Move, Rotate, and Scale gizmos; drag a selected object to apply the active transform','Remappable directions move the full selection on X/Z; Primary raises and Secondary lowers','G groups a multi-selection; U ungroups; Material and transform tools apply across the current selection','Export Code creates a portable scene code; Import Code restores a shared scene and remains undoable','Undo/Redo supports up to 80 edits; Ctrl/Cmd+Z and Ctrl/Cmd+Y are supported','Snap cycles 0.25 / 0.50 / 1.00 grid spacing and scenes autosave locally','Complete all seven certification blueprints, including grouped modular and pavilion briefs']},
  {id:'neon-serpent',title:'Neon Serpent: Gridfall',tagline:'Classic snake first. Gridfall chaos later.',description:'A four-mode snake game that starts with a pure classic grow-and-survive contract, then layers in drones, relay gates, combo scoring, gold sparks, and rechargeable collision phase.',objective:'Steer the serpent into cyan sparks to grow and reach each contract length goal without hitting your own body. Clear Classic Snake first, then master the three remix contracts.',genres:['Snake','Arcade','Action','Survival','Score Attack'],added:'2026-10-01',updated:'2026-10-02',version:'2.0',featured:false,basePopularity:390,cover:'covers/neon-serpent.svg',path:'games/neon-serpent/index.html',accent:'#22d3ee',remappable:true,scoreMeta:{unit:'pts',direction:'high',label:'Gridfall score'},controls:['Arrow keys or WASD always steer the serpent; custom remaps also remain valid','Contract 1 is pure Classic Snake with no drones or relay gates','Primary arms collision phase while charge remains','Secondary temporarily brakes for precise routing','Later contracts add moving drones and paired relay gates','Touch controls supported','1–4 selects an unlocked contract; P pauses; R restarts the current contract']},
  {id:'pulse-maze',title:'Pulse Maze',tagline:'Clear the shards. Flip the hunt. Master the maze.',description:'An original three-maze chase arcade game with signal shards, four distinct Prism Hunter behaviors, temporary power reversals, bonus fruit, escalating speed, touch controls, gamepad support, and persistent local bests.',objective:'Collect every cyan signal shard while avoiding the Prism Hunters. Corner pulse nodes temporarily let you overpower hunters. Clear all three mazes to complete the run.',genres:['Maze Chase','Arcade','Action','Score Attack'],added:'2026-10-02',updated:'2026-10-02',version:'1.0',featured:true,basePopularity:430,cover:'covers/pulse-maze.svg',path:'games/pulse-maze/index.html',accent:'#67e8f9',remappable:true,scoreMeta:{unit:'pts',direction:'high',label:'Maze score'},controls:['Arrow keys or WASD always steer; custom remaps also remain valid','Collect every cyan shard to clear the current maze','Corner pulse nodes temporarily make Prism Hunters vulnerable','Yellow bonus signal fruit appears late in a maze for extra score','P pauses and R restarts the current maze','Touch directions and gamepad movement supported']},
  {
    id: 'fluxward-conclave', title: 'Fluxward Conclave', tagline: 'Charge the lattice. Capture the relays. Hold the field.',
    description: 'A three-arena turn-based territory strategy game. Extend a charged lattice, reinforce cells into conversion pulses, seize bonus-action relays, outscore a tactical AI campaign, or pass the controls for a local duel.',
    genres: ['Territory', 'Turn-Based', 'Competitive', 'Board', 'Multiplayer'], added: '2026-10-01', updated: '2026-10-01', version: '1.0', featured: false, basePopularity: 282,
    cover: 'covers/fluxward-conclave.svg', path: 'games/fluxward-conclave/index.html', accent: '#67e8f9', remappable: true, modes: ['Solo', 'Local Multiplayer'],
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Conclave score' },
    controls: ['Remappable directions move the lattice cursor', 'Primary selects a friendly cell and extends into an adjacent open tile', 'Secondary charges a friendly cell; charge 3 releases a conversion pulse', 'Enter ends the current turn; M toggles Solo Campaign and Local Duel', 'Pointer and touch board controls plus mobile action buttons supported', 'Gamepad stick or D-pad + A/B and Start supported', 'R restarts the current campaign or duel']
  },
  {
    id: 'strata-cipher', title: 'Strata Cipher', tagline: 'Read the layer. Protect the site. Recover the story.',
    description: 'A six-site archaeology and excavation strategy puzzle. Survey buried strata, triangulate artifact signals, avoid fault pockets, preserve site integrity, and archive eighteen fragments with the fewest destructive digs.',
    genres: ['Archaeology', 'Excavation', 'Puzzle', 'Strategy'], added: '2026-10-01', updated: '2026-10-01', version: '1.0', featured: false, basePopularity: 264,
    cover: 'covers/strata-cipher.svg', path: 'games/strata-cipher/index.html', accent: '#f59e0b', remappable: true,
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Excavation score' },
    controls: ['Remappable directions move the excavation cursor', 'Primary excavates the selected tile', 'Secondary surveys nearby strata and reveals artifact-signal counts', 'Touch grid selection and controls supported', 'Gamepad left stick + A/B supported', 'R restarts the full expedition']
  },
  {
    id: 'echofall-caverns', title: 'Echofall Caverns', tagline: 'Map the dark by sound.',
    description: 'A six-chamber echolocation exploration puzzle. Send sonar pulses to reveal nearby stone, recover three resonators in each cavern, and seal the atlas with the lowest possible echo cost.',
    genres: ['Echolocation', 'Navigation', 'Puzzle', 'Exploration'], added: '2026-10-01', featured: false, basePopularity: 206,
    cover: 'covers/echofall-caverns.svg', path: 'games/echofall-caverns/index.html', accent: '#22d3ee', remappable: true, version: '1.0',
    scoreMeta: { unit: 'echo', direction: 'low', label: 'Echo cost' },
    controls: ['Remappable directional keys move one cavern tile', 'Primary sends a sonar pulse that reveals nearby terrain', 'Secondary waits one turn without spending an echo', 'Recover all three resonators before entering each exit', 'Touch controls and gamepad supported', 'R restarts the six-chamber expedition', 'Lower echo cost is better']
  },
  {
    id: 'starfall-observatory', title: 'Starfall Observatory', tagline: 'Acquire the bearing. Match the spectrum. Seal the night.',
    description: 'A six-target astronomy and precision observation game. Align azimuth and altitude, choose the correct spectral filter, capture clean observations, and complete an Architect Industries night survey.',
    genres: ['Astronomy', 'Observation', 'Simulation', 'Precision'], added: '2026-10-01', updated: '2026-10-01', version: '1.0', featured: false, basePopularity: 252,
    cover: 'covers/starfall-observatory.svg', path: 'games/starfall-observatory/index.html', accent: '#7dd3fc', remappable: true,
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Observatory score' },
    controls: ['Remappable Left / Right adjusts azimuth', 'Remappable Up / Down adjusts altitude', 'Secondary cycles Blue, Gold, and Infrared filters', 'Primary captures the current observation', 'Tap or click the scope to point directly', 'Touch controls supported', 'R restarts the night survey']
  },
  {
    id: 'prismweave-atelier', title: 'Prismweave Atelier', tagline: 'Shift the warp. Match the commission.',
    description: 'A six-commission textile logic game. Rotate whole warp rows and weft columns to restore scrambled three-color patterns, chase par moves, and complete the Architect Industries prism atelier.',
    genres: ['Weaving', 'Pattern', 'Logic', 'Puzzle'], added: '2026-09-30', updated: '2026-09-30', version: '1.0', featured: false, basePopularity: 246,
    cover: 'covers/prismweave-atelier.svg', path: 'games/prismweave-atelier/index.html', accent: '#c084fc', remappable: true,
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Atelier score' },
    controls: ['Remappable Left / Right selects a row or column band', 'Remappable Up / Down switches between Rows and Columns', 'Primary shifts the selected band forward', 'Secondary shifts the selected band backward', 'Pointer and touch controls supported', 'R resets the current commission']
  },
  {
    id: 'blackglass-watch', title: 'Blackglass Watch', tagline: 'Six cameras. Seven anomalies. Trust the baseline.',
    description: 'A seven-anomaly surveillance horror game. Compare six station feeds, classify figures, lighting shifts, displaced objects, and unnatural movement, manage rising stress, and finish the night watch cleanly.',
    genres: ['Horror', 'Observation', 'Strategy', 'Atmospheric'], added: '2026-09-30', updated: '2026-09-30', version: '1.0', featured: false, basePopularity: 238,
    cover: 'covers/blackglass-watch.svg', path: 'games/blackglass-watch/index.html', accent: '#82c7c4', remappable: true,
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Watch score' },
    controls: ['Remappable Left / Right changes camera', 'Remappable Up / Down changes report type', 'Primary files the selected anomaly report', 'Secondary steadies station stress twice per watch', 'Pointer and touch controls supported', 'R restarts the watch']
  },
  {
    id: 'tetherline-salvage', title: 'Tetherline Salvage', tagline: 'Hook the drift. Tow the prize. Keep the hull intact.',
    description: 'A real-time orbital salvage run. Pilot a recovery craft through drifting hazards, hook six cargo pods with a physics tether, manage momentum, and tow every prize into the recovery bay before the shift expires.',
    genres: ['Salvage', 'Space', 'Physics', 'Action'], added: '2026-09-30', updated: '2026-09-30', version: '1.0', featured: false, basePopularity: 221,
    cover: 'covers/tetherline-salvage.svg', path: 'games/tetherline-salvage/index.html', accent: '#60a5fa', remappable: true,
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Salvage score' },
    controls: ['Remappable directions pilot the recovery craft', 'Primary hooks or releases nearby salvage', 'Secondary fires the inertial brake', 'Gamepad left stick + A/B supported', 'Touch flight, tether, and brake controls on mobile', 'Recover all six pods before time or hull runs out']
  },
  {
    id: 'kiteglass-drift', title: 'Kiteglass Drift', tagline: 'Read the crosswind. Hold the gate line.',
    description: 'A seven-gate gliding time trial with momentum flight, shifting crosswind, thermal columns, missed-gate penalties, gamepad support, touch controls, remappable pitch, and lower-is-better adjusted times.',
    genres: ['Gliding', 'Flight', 'Racing', 'Sports'], added: '2026-09-30', updated: '2026-09-30', version: '1.0', featured: false, basePopularity: 232,
    cover: 'covers/kiteglass-drift.svg', path: 'games/kiteglass-drift/index.html', accent: '#67e8f9', remappable: true,
    scoreMeta: { unit: 'sec', direction: 'low', label: 'Adjusted glide time' },
    controls: ['Remappable Up / Down adjusts pitch', 'Primary / Space flares and levels the wing', 'Gamepad left stick + A supported', 'Touch pitch and flare controls on mobile', 'Thread seven suspended gates; missed gates add six seconds', 'Lower adjusted time is better']
  },
  {
    id: 'runelight-locksmith', title: 'Runelight Locksmith', tagline: 'Listen for the bright window. Set the pin.',
    description: 'A six-lock mechanical timing game. Select moving pins, read their cyan set windows, commit at the right instant, absorb slips, and open the Runelight vault with as few misses as possible.',
    objective: 'Open all six Runelight locks by setting each moving pin inside its cyan timing window while minimizing misses.',
    genres: ['Lockpicking', 'Mechanical', 'Timing', 'Puzzle'], added: '2026-09-30', updated: '2026-09-30', version: '1.0', featured: false, basePopularity: 215,
    cover: 'covers/runelight-locksmith.svg', path: 'games/runelight-locksmith/index.html', accent: '#a78bfa', remappable: true,
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Vault score' },
    controls: ['Remappable Left / Right selects a pin', 'Primary / Space sets the selected pin', 'Tap or click a pin to select it', 'Catch each moving needle inside its cyan set window', 'R restarts the vault']
  },
  {
    id: 'mirrormesh-relay', title: 'Mirrormesh Relay', tagline: 'Turn the light. Close the mesh.',
    description: 'A six-relay optics puzzle about rotating mirrors, touching every beacon, and steering a live beam into its receiver with as few turns as possible.',
    genres: ['Optics', 'Logic', 'Puzzle', 'Physics'], added: '2026-09-30', featured: false, basePopularity: 204,
    cover: 'covers/mirrormesh-relay.svg', path: 'games/mirrormesh-relay/index.html', accent: '#67e8f9', remappable: true,
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Relay score' },
    controls: ['Remappable directions move the cursor', 'Primary / Space rotates the selected mirror', 'Tap or click a mirror to rotate it', 'R resets the current relay']
  },
  {
    id: 'hushwave-operator', title: 'Hushwave Operator', tagline: 'Find the carrier beneath the noise.',
    description: 'A six-signal radio tuning puzzle. Adjust frequency, phase, and gain, read the scope, follow diagnostic hints, and lock increasingly narrow hidden carriers.',
    objective: 'Decode all six hidden radio carriers by tuning frequency, phase, and gain closely enough to achieve a stable lock.',
    genres: ['Signal', 'Radio', 'Simulation', 'Puzzle'], added: '2026-09-30', featured: false, basePopularity: 196,
    cover: 'covers/hushwave-operator.svg', path: 'games/hushwave-operator/index.html', updated: '2026-10-01', version: '1.1', accent: '#a78bfa', remappable: true,
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Decode score' },
    controls: ['Remappable Left / Right adjusts the selected control', 'Remappable Up / Down changes control', 'Primary / Space samples the carrier', 'Pointer and touch sliders supported', 'R restarts the band']
  },
  {
    id: 'pulsevine-parkour', title: 'Pulsevine Parkour', tagline: 'Five courses. One pulse.',
    description: 'A five-course rooftop parkour campaign with progressively harder checkpoint lines, momentum movement, coyote-time jumps, thorn gauntlets, launch pads, crosswinds, persistent course unlocks and best times, gamepad/touch support, and lower-is-better scoring.',
    objective: 'Reach every checkpoint and finish line across all five courses; unlock the next course and minimize each course time plus the five-course total.',
    genres: ['Parkour', 'Platformer', 'Traversal', 'Speedrun'], added: '2026-09-30', updated: '2026-10-01', version: '2.0', featured: false, basePopularity: 236,
    cover: 'covers/pulsevine-parkour.svg', path: 'games/pulsevine-parkour/index.html', accent: '#6ee7b7', remappable: true,
    scoreMeta: { unit: 'sec', direction: 'low', label: 'Course time' },
    controls: ['Arrow Left/Right or A/D always move; a saved custom remap remains an additional movement option', 'Space jumps by default with coyote-time forgiveness; Primary is remappable and ↑ also jumps', 'R restarts the current course', 'Number keys 1-5 select unlocked courses', 'N advances to the next unlocked course after a clear', 'Gamepad: left stick moves, A jumps, Start restarts, Y advances after a clear', 'Touch: LEFT / RIGHT / JUMP / RESET / NEXT buttons on mobile', 'Clear all five courses; lower course and five-course best-total times are better']
  },
  {
    id: 'tessera-commons', title: 'Tessera Commons', tagline: 'Draft a district where every edge has a neighbor.',
    description: 'A ten-round board-inspired tile-placement strategy game. Draft paired civic symbols, grow a connected commons, score cooperative adjacencies, preserve four-way diversity, and build a stronger final district.',
    genres: ['Tile Placement', 'Board', 'Strategy', 'Puzzle'], added: '2026-09-30', updated: '2026-09-30', version: '1.0', featured: false, basePopularity: 207,
    cover: 'covers/tessera-commons.svg', path: 'games/tessera-commons/index.html', accent: '#fbbf24', remappable: true,
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Commons score' },
    controls: ['Tap or click a board space and draft tile', 'Remappable directions move the board cursor', 'Primary places the selected tile', 'Secondary cycles the three-tile offer', 'R starts a new table', 'Build ten connected tiles and maximize adjacency plus symbol diversity']
  },
  {
    id: 'glasswing-polo', title: 'Glasswing Polo', tagline: 'Bank the wing. Break the line. Own the goal.',
    description: 'A fast hover-ball sport for solo play against a tracking AI or same-device competition. Drive momentum, body the glowing ball, use timed dash bursts, and win a first-to-five arena match.',
    genres: ['Hover Sport', 'Sports', 'Competitive', 'Physics'], added: '2026-09-30', updated: '2026-09-30', version: '1.0', featured: false, basePopularity: 216,
    cover: 'covers/glasswing-polo.svg', path: 'games/glasswing-polo/index.html', accent: '#5eead4', remappable: true, modes: ['Solo','Local Multiplayer'],
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Match score' },
    controls: ['P1 uses remappable directional controls', 'Primary triggers a dash burst', 'Solo mode includes a tracking arena AI', 'Local 2P adds Arrow keys + Enter for P2', 'Touch pads support mobile play', 'Gamepads supported through browser input when available', 'R restarts the match']
  },
  {
    id: 'rootsong-architect', title: 'Rootsong Architect', tagline: 'Every branch spends growth. Every node changes the grove.',
    description: 'A six-garden ecological network puzzle. Grow a connected root system through water and nutrient nodes, route around stone, budget costly clay growth, reclaim bad branches, and awaken each blossom.',
    genres: ['Botany', 'Network', 'Puzzle', 'Nature'], added: '2026-09-30', updated: '2026-09-30', version: '1.0', featured: false, basePopularity: 198,
    cover: 'covers/rootsong-architect.svg', path: 'games/rootsong-architect/index.html', accent: '#86efac', remappable: true,
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Grove score' },
    controls: ['Tap or click a soil cell adjacent to the living network', 'Remappable directions move the garden cursor', 'Primary grows into the selected cell', 'Secondary / Backspace reclaims the most recent branch', 'Clay costs two growth instead of one', 'R resets the current garden']
  },
  {
    id: 'stoneveil-ascent', title: 'Stoneveil Ascent', tagline: 'Read the wall. Spend your grip. Earn the summit.',
    description: 'A five-route climbing and route-finding game about reachable holds, stamina budgeting, chalk timing, fall recovery, and efficient summit lines. Supports remappable keyboard controls, pointer/touch play, and gamepad input.',
    genres: ['Climbing', 'Mountaineering', 'Sports', 'Precision'], added: '2026-09-30', featured: false, basePopularity: 204,
    cover: 'covers/stoneveil-ascent.svg', path: 'games/stoneveil-ascent/index.html', accent: '#67e8f9', remappable: true,
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Ascent score' },
    controls: ['Click or tap a glowing reachable hold to climb directly', 'Remappable Left / Right cycles safe holds', 'Remappable Up chooses the highest safe hold', 'Primary commits the selected climb', 'Secondary uses one chalk refill per route', 'Gamepad stick + A/B supported', 'R returns to the belay with a fall penalty']
  },
  {
    id: 'tidal-foundry', title: 'Tidal Foundry', tagline: 'Restore pressure one channel at a time.',
    description: 'A six-commission hydraulic routing puzzle. Rotate channel plates, trace pressure from source to receiver, diagnose breaks, and commission the foundry efficiently with keyboard, pointer, or touch controls.',
    objective: 'Restore all six foundry commissions by rotating channel plates until pressure can flow continuously from each source to its receiver.',
    genres: ['Hydraulics', 'Engineering', 'Logic', 'Puzzle'], added: '2026-09-30', featured: false, basePopularity: 190,
    cover: 'covers/tidal-foundry.svg', path: 'games/tidal-foundry/index.html', accent: '#5eead4', remappable: true,
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Foundry score' },
    controls: ['Tap or click a channel plate to rotate it', 'Remappable directions move the keyboard cursor', 'Primary rotates the selected plate', 'Secondary tests pressure flow', 'R resets the current commission', 'Restore all six commissions efficiently']
  },
  {
    id: 'riftwake-regatta', title: 'Riftwake Regatta', tagline: 'Read the wind. Trim the sail. Beat the harbor rival.',
    description: 'A wind-driven sailing race through seven harbor gates with sail-trim efficiency, shifting wind, rock hazards, a moving rival boat, touch controls, gamepad support, remappable steering, and lower-is-better adjusted time.',
    genres: ['Sailing', 'Racing', 'Sports', 'Simulation'], added: '2026-09-30', featured: false, basePopularity: 196,
    cover: 'covers/riftwake-regatta.svg', path: 'games/riftwake-regatta/index.html', accent: '#67e8f9', remappable: true,
    scoreMeta: { unit: 'sec', direction: 'low', label: 'Regatta time' },
    controls: ['Remappable Left / Right steers the hull', 'Remappable Up / Down adjusts sail trim', 'Primary / Space performs a quick tack', 'Gamepad left stick + A supported', 'Touch controls on mobile', 'Clear all seven gates in order; lower adjusted time is better']
  },
  {
    id: 'archive-alchemist', title: 'Archive Alchemist', tagline: 'Every failed brew is evidence.',
    description: 'A six-commission crafting deduction game. Combine exactly two reagents, match four target properties, use failed mixtures as notebook evidence, and restore the archive with as few mistakes as possible.',
    genres: ['Alchemy', 'Crafting', 'Logic', 'Puzzle'], added: '2026-09-30', featured: false, basePopularity: 184,
    cover: 'covers/archive-alchemist.svg', path: 'games/archive-alchemist/index.html', accent: '#c4b5fd',
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Archive score' },
    controls: ['Tap or click two reagent vials', 'Keys 1-6 toggle reagents', 'Enter brews the selected pair', 'Failed mixtures remain in the notebook as evidence', 'R restarts the archive']
  },
  {
    id: 'driftglass-links', title: 'Driftglass Links', tagline: 'Read the bank. Trust the roll.',
    description: 'A six-hole precision golf and physics game with drag-to-shoot aiming, ricochet walls, sand, water hazards, gamepad support, and lower-is-better stroke scoring.',
    genres: ['Golf', 'Sports', 'Physics', 'Precision'], added: '2026-09-30', featured: false, basePopularity: 188,
    cover: 'covers/driftglass-links.svg', path: 'games/driftglass-links/index.html', accent: '#5eead4',
    scoreMeta: { unit: 'strokes', direction: 'low', label: 'Course strokes' },
    controls: ['Drag from the ball to aim and set shot power', 'Arrow Left / Right adjusts aim and Up / Down adjusts power', 'Space takes the shot', 'Gamepad left stick aims, triggers change power, and A shoots', 'Touch and pointer play supported', 'R restarts the course', 'Lower stroke totals are better']
  },
  {
    id: 'tideglass-surveyor', title: 'Tideglass Surveyor', tagline: 'Three lighthouses. One hidden coordinate.',
    description: 'A six-chart cartography logic game. Triangulate hidden waymarks from three Manhattan-distance lighthouse readings, manage a four-probe budget, and seal the atlas efficiently.',
    genres: ['Cartography', 'Logic', 'Puzzle', 'Exploration'], added: '2026-09-30', featured: false, basePopularity: 178,
    cover: 'covers/tideglass-surveyor.svg', path: 'games/tideglass-surveyor/index.html', accent: '#7dd3fc',
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Survey score' },
    controls: ['Click or tap any grid sector to move the survey cursor', 'Arrow keys move the cursor one sector', 'Enter / Space probes the selected sector', 'Use all three lighthouse distance readings to triangulate the hidden waymark', 'R resets the current chart']
  },
  {
    id: 'spanwright', title: 'Spanwright', tagline: 'Build the load path. Prove the span.',
    description: 'A five-blueprint construction and engineering puzzle about budgeting beams, creating load-bearing triangles, connecting banks, and certifying each structure with a moving convoy test.',
    genres: ['Construction', 'Engineering', 'Physics', 'Puzzle'], added: '2026-09-30', featured: false, basePopularity: 181,
    cover: 'covers/spanwright.svg', path: 'games/spanwright/index.html', accent: '#2dd4bf',
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Engineering score' },
    controls: ['Tap or click one joint and then another to place a beam', 'T or Space tests the current span', 'Backspace removes the last beam', 'R resets the blueprint', 'Build connected, well-braced structures without exceeding the budget']
  },
  {
    id: 'lantern-line', title: 'Lantern Line', tagline: 'Smooth stops. Quiet streets. Zero excuses.',
    description: 'A city-loop vehicle simulation about throttle, braking, passenger comfort, schedule discipline, and six precise station stops. Finish the route with the lowest total service delay.',
    genres: ['Vehicle Simulation', 'Transit', 'Logistics', 'Simulation'], added: '2026-09-30', featured: false, basePopularity: 174,
    cover: 'covers/lantern-line.svg', path: 'games/lantern-line/index.html', accent: '#fb7185', remappable: true,
    scoreMeta: { unit: 'sec', direction: 'low', label: 'Service delay' },
    controls: ['Remappable Up accelerates and Down brakes', 'Primary / Space opens doors when stopped at a platform', 'R restarts the shift', 'Gamepad triggers + A supported', 'Touch throttle, brake, and doors controls on mobile', 'Lower service-delay scores are better']
  },
  {
    id: 'frostline-rescue', title: 'Frostline Rescue', tagline: 'Contain the fire. Bring everyone home.',
    description: 'A real-time emergency rescue game with spreading fire, stranded residents, water management, a safe-zone escort loop, procedural audio, touch controls, gamepad support, and remappable keyboard movement.',
    genres: ['Rescue', 'Emergency', 'Action', 'Strategy'], added: '2026-09-30', featured: false, basePopularity: 178,
    cover: 'covers/frostline-rescue.svg', path: 'games/frostline-rescue/index.html', accent: '#22d3ee', remappable: true,
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Rescue score' },
    controls: ['Move with remappable directional keys or Arrow keys before customization', 'Primary sprays water at nearby fire', 'Secondary / Enter escorts a nearby resident or secures them at the safe zone', 'Refill water near the blue hydrant', 'Gamepad left stick + A/B supported', 'Touch controls on mobile']
  },
  {
    id: 'signal-choir', title: 'Signal Choir', tagline: 'Hear it. See it. Return the pattern.',
    description: 'A six-round audiovisual memory game with five tonal channels, escalating sequences, replay penalties, streak scoring, three lives, and a complete visual mode for muted play.',
    genres: ['Memory', 'Music', 'Puzzle', 'Relaxing'], added: '2026-09-30', featured: false, basePopularity: 163,
    cover: 'covers/signal-choir.svg', path: 'games/signal-choir/index.html', updated: '2026-10-01', version: '1.1', accent: '#a78bfa',
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Memory score' },
    controls: ['Keys 1-5 repeat the five signal channels', 'Tap or click the five pads on touch/pointer devices', 'Replay Signal repeats the current pattern for a score penalty', 'R restarts the choir']
  },
  {
    id: 'terrace-keeper', title: 'Terrace Keeper', tagline: 'Plant carefully. Let the weather work.',
    description: 'A twelve-day farming and management simulation. Plant three crop types, water terraces, harvest for profit, react to frost and rain, and invest in a cistern or windglass to fulfill the seasonal contract.',
    objective: 'Complete the twelve-day seasonal contract by planting, watering, harvesting, weather-proofing, and investing well enough to finish with a profitable terrace farm.',
    genres: ['Farming', 'Agriculture', 'Management', 'Relaxing'], added: '2026-09-30', featured: false, basePopularity: 158,
    cover: 'covers/terrace-keeper.svg', path: 'games/terrace-keeper/index.html', accent: '#86efac',
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Terrace score' },
    controls: ['Tap or click a seed type, then an empty terrace to plant', 'Tap planted crops to water them or harvest when ready', 'End Day advances crop growth and weather', 'Optional cistern and windglass upgrades change the season economy']
  },
  {
    id: 'chronofold-courier', title: 'Chronofold Courier', tagline: 'Cooperate with the route you already took.',
    description: 'A five-fold time-loop puzzle where every sealed route becomes an echo that repeats your moves. Coordinate past versions of yourself across pressure plates, walls, and phase-locked exits.',
    genres: ['Time Loop', 'Puzzle', 'Strategy', 'Experimental'], added: '2026-09-30', featured: false, basePopularity: 166,
    cover: 'covers/chronofold-courier.svg', path: 'games/chronofold-courier/index.html', accent: '#c4b5fd', remappable: true,
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Archive score' },
    controls: ['WASD / Arrow keys move one grid step', 'Space seals the current route into a replaying echo', 'X / Period waits one step for synchronization', 'R restarts the full archive', 'Touch direction, wait, and loop controls on mobile']
  },
  {
    id: 'hearthline-kitchen', title: 'Hearthline Kitchen', tagline: 'Read the rail. Hit the heat. Keep service moving.',
    description: 'A seventy-five second cooking and time-management rush. Assemble four recipes, stop the heat meter at the right moment, protect your combo, and serve as many accurate plates as possible.',
    genres: ['Cooking', 'Time Management', 'Management', 'Arcade'], added: '2026-09-30', featured: false, basePopularity: 157,
    cover: 'covers/hearthline-kitchen.svg', path: 'games/hearthline-kitchen/index.html', accent: '#fb923c',
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Service score' },
    controls: ['Keys 1-6 or touch ingredient stations add ingredients', 'C cooks the prepared bowl', 'Enter serves the plate', 'X / Backspace clears the bowl', 'R restarts after service closes']
  },
  {
    id: 'spectra-safari', title: 'Spectra Safari', tagline: 'Track the wild. Frame the moment.',
    description: 'A relaxing wildlife-photography expedition with six species, rarity scoring, framing and distance bonuses, twelve shots of film, roaming creatures, procedural audio, touch controls, and gamepad support.',
    genres: ['Photography', 'Nature', 'Exploration', 'Relaxing'], added: '2026-09-30', featured: false, basePopularity: 153,
    cover: 'covers/spectra-safari.svg', path: 'games/spectra-safari/index.html', accent: '#86efac',
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Survey score' },
    controls: ['WASD / Arrow keys pan the field camera', 'Space takes a photograph', 'Frame wildlife near the center reticle for stronger scores', 'Gamepad left stick + A supported', 'Touch movement and PHOTO controls on mobile']
  },
  {
    id: 'ashfall-caravan', title: 'Ashfall Caravan', tagline: 'Carry the people. Spend the future carefully.',
    description: 'A twelve-crossing narrative-management journey with three persistent road contracts, Chronicle traits, route variants, expanded resource pressure, and distinct endings. Master Relief, Survey, and Courier runs across repeat journeys.',
    genres: ['Narrative', 'Adventure', 'Management', 'Interactive Fiction'], added: '2026-09-30', updated: '2026-10-01', version: '2.0', featured: false, basePopularity: 191,
    cover: 'covers/ashfall-caravan.svg', path: 'games/ashfall-caravan/index.html', accent: '#fb7185', remappable: true,
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Journey score' },
    controls: ['Choose one of three persistent road contracts before departure', 'Primary chooses the first decision; Secondary chooses the second', 'Keys 1 / 2 remain available for decisions', 'Tap or click contract and choice cards on touch devices', 'Gamepad A/B supported', 'Completed journeys unlock Chronicle traits, route variants, endings, and contract mastery', 'R restarts after the journey ends']
  },
  {
    id: 'twinforge-expedition', title: 'Twinforge Expedition', tagline: 'Two pilots. One forge. Three sectors.',
    description: 'A same-device cooperative expedition for two players. Gather shared ore and crystal, evade moving hazards, manage one energy reserve, and dock together to build three forge relays.',
    genres: ['Co-op', 'Multiplayer', 'Exploration', 'Survival'], added: '2026-09-30', featured: false, basePopularity: 151,
    cover: 'covers/twinforge-expedition.svg', path: 'games/twinforge-expedition/index.html', accent: '#67e8f9',
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Team score' },
    controls: ['Player 1: WASD + F to build', 'Player 2: Arrow keys + / to build', 'Dual touch controls are available on mobile', 'Two gamepads supported when connected', 'Both players must dock and hold build together']
  },
  {
    id: 'mothlight-museum', title: 'Mothlight Museum', tagline: 'Find what the archive forgot.',
    description: 'A three-room hidden-object investigation with fifteen hand-placed exhibits, hint penalties, room-clear bonuses, touch/pointer play, and a final case score based on speed and observation.',
    genres: ['Hidden Object', 'Mystery', 'Puzzle', 'Observation'], added: '2026-09-30', featured: false, basePopularity: 146,
    cover: 'covers/mothlight-museum.svg', path: 'games/mothlight-museum/index.html', accent: '#c4b5fd',
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Case score' },
    controls: ['Click or tap listed exhibits in each gallery', 'H or the Hint button reveals one target for a score penalty', 'R restarts the investigation']
  },
  {
    id: 'windward-cargo',
    title: 'Windward Cargo',
    tagline: 'Read the sky. Protect the payload.',
    description: 'A momentum-based flight and delivery game with shifting wind fields, fuel management, cargo integrity, gentle landing requirements, four escalating routes, procedural audio, touch controls, and gamepad support.',
    genres: ['Flight', 'Delivery', 'Physics', 'Arcade'],
    added: '2026-09-30', updated: '2026-09-30', version: '1.1', featured: false, basePopularity: 142,
    cover: 'covers/windward-cargo.svg', path: 'games/windward-cargo/index.html', accent: '#38bdf8', remappable: true,
    controls: ['Remappable Up applies thrust', 'Remappable Left / Right changes pitch', 'Primary boosts at higher fuel cost', 'Fly through cyan pickup rings and land gently in gold delivery rings', 'Touch controls on mobile', 'Gamepad left stick + A/B supported'], scoreMeta:{unit:'pts',direction:'high',label:'flight score'}
  },
  {
    id: 'cipher-court',
    title: 'Cipher Court',
    tagline: 'Every clue narrows the room.',
    description: 'A four-case deduction game. Compare suspect traits against evidence, reveal extra clues at a score cost, avoid false accusations, and close the full docket with the strongest possible reasoning score.',
    genres: ['Deduction', 'Mystery', 'Logic', 'Puzzle'],
    added: '2026-09-30', featured: false, basePopularity: 136,
    cover: 'covers/cipher-court.svg', path: 'games/cipher-court/index.html', accent: '#c084fc',
    controls: ['Click or tap a suspect to select them', 'Accuse selected suspect when the evidence fits', 'Reveal another clue costs score', 'Enter accuses / Space reveals another clue', 'R restarts the docket'], scoreMeta:{unit:'pts',direction:'high',label:'deduction score'}
  },
  {
    id: 'moonwake-angler',
    title: 'Moonwake Angler',
    tagline: 'Cast by moonlight. Read the tension.',
    description: 'A relaxed fishing game with bite timing, line-tension management, five fish species, species values, a 90-second night haul, procedural audio, touch input, and gamepad support.',
    genres: ['Fishing', 'Relaxing', 'Simulation'],
    added: '2026-09-30', featured: false, basePopularity: 132,
    cover: 'covers/moonwake-angler.svg', path: 'games/moonwake-angler/index.html', accent: '#93c5fd',
    controls: ['Space / CAST throws the line', 'Reel when the float flashes', 'Hold and release REEL to keep tension below the red zone', 'R restarts the night haul', 'Touch controls on mobile', 'Gamepad A supported'], scoreMeta:{unit:'pts',direction:'high',label:'haul score'}
  },
  {
    id: 'deepwater-signal', title: 'Deepwater Signal', tagline: 'Ping the dark. Wake nothing.',
    description: 'A sonar-stealth undersea expedition. Synchronize five drowned relays, manage battery and hull, evade sound-hunting predators, and return to the surface gate with the strongest survey score.',
    genres: ['Underwater', 'Stealth', 'Exploration', 'Simulation'], added: '2026-09-30', updated: '2026-09-30', version: '1.1', featured: false, basePopularity: 132,
    cover: 'covers/deepwater-signal.svg', path: 'games/deepwater-signal/index.html', accent: '#67e8f9', remappable: true,
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Mission score' },
    controls: ['Remappable directions pilot the submersible', 'Primary fires a sonar pulse', 'Secondary scans a nearby relay or exits at the surface gate', 'Gamepad left stick + A ping / B scan supported', 'Touch movement, ping, and scan controls on mobile', 'R restarts the mission']
  },
  {
    id: 'emberdeck-pilgrim', title: 'Emberdeck Pilgrim', tagline: 'Carry a living deck through five furnace gates.',
    description: 'A branching five-gate deckbuilding roguelike with readable enemy intent, route-shaped encounters, three furnace relics, legacy boons, persistent dual-route mastery, expanded card rewards, and score pressure from health and run time.',
    genres: ['Deckbuilder', 'Card', 'Roguelike', 'Strategy'], added: '2026-09-30', updated: '2026-10-01', version: '1.3', featured: false, basePopularity: 182,
    cover: 'covers/emberdeck-pilgrim.svg', path: 'games/emberdeck-pilgrim/index.html', accent: '#fb923c', remappable: true,
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Pilgrimage score' },
    controls: ['Digits 1-5 or tap play cards directly', 'Remappable Left / Right selects a card', 'Primary plays the selected card', 'Secondary ends the current turn', 'Choose Glass or Iron route after gate one and bind a relic after gate two', 'Complete both routes across runs to master the pilgrimage', 'R restarts the pilgrimage']
  },
  {
    id: 'command-bloom', title: 'Command Bloom', tagline: 'Program the garden one instruction at a time.',
    description: 'A six-stage programming logic puzzle about building short command queues, rotating a drone, navigating root walls, pulsing energy cores, and reaching each green gate efficiently.',
    genres: ['Programming', 'Logic', 'Puzzle'], added: '2026-09-30', featured: false, basePopularity: 127,
    cover: 'covers/command-bloom.svg', path: 'games/command-bloom/index.html', accent: '#86efac',
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Program score' },
    controls: ['F/L/R/P add Forward, Left, Right, and Pulse commands', 'Enter runs the queued program', 'Backspace removes the last instruction', 'Tap/click controls support touch and pointer play', 'Escape resets the current stage or restarts after completion']
  },
  {
    id: 'railspire-dispatch',
    title: 'Railspire Dispatch',
    tagline: 'Four switches. One network. No collisions.',
    description: 'A fast logistics-routing game about reading rail flow, toggling switches, matching colored trains to depots, and keeping a busy elevated network collision-free.',
    objective: 'Route each colored train to its matching depot while preventing collisions and wrong-depot strikes; three strikes end the shift.',
    genres: ['Logistics', 'Strategy', 'Puzzle'],
    added: '2026-09-30', featured: false, basePopularity: 126,
    cover: 'covers/railspire-dispatch.svg', path: 'games/railspire-dispatch/index.html', accent: '#a7f3d0',
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Dispatch score' },
    controls: ['Keys 1-4 toggle the four rail switches', 'Tap amber switches or on-screen switch buttons', 'Route each colored train to its matching depot', 'Avoid three strikes from wrong depots or collisions', 'R restarts the shift']
  },
  {
    id: 'glyphsmith', title: 'Glyphsmith', tagline: 'Forge words before the archive cools.',
    description: 'A sixty-second word-forging sprint. Type or tap runes to recreate the target word, build combo chains, and keep the archive alive under a fast countdown.',
    genres: ['Word', 'Typing', 'Puzzle'], added: '2026-09-30', featured: false, basePopularity: 123,
    cover: 'covers/glyphsmith.svg', path: 'games/glyphsmith/index.html', updated: '2026-10-01', version: '1.1', accent: '#e879f9',
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Forge score' },
    controls: ['Type letters on a keyboard or tap the rune bank', 'Enter forges the current word', 'Backspace removes the last rune', 'Escape clears the entry', 'R restarts after the archive closes']
  },
  {
    id: 'solar-loom', title: 'Solar Loom', tagline: 'Build a stable little universe.',
    description: 'An experimental orbital sandbox about placing different world types, balancing gravitational mass, maximizing habitability, and shepherding a tiny solar system through eight epochs.',
    genres: ['Sandbox', 'Experimental', 'Simulation', 'Strategy'], added: '2026-09-30', featured: false, basePopularity: 121,
    cover: 'covers/solar-loom.svg', path: 'games/solar-loom/index.html', accent: '#93c5fd',
    scoreMeta: { unit: 'pts', direction: 'high', label: 'System score' },
    controls: ['Tap or click an orbit to place the selected world', 'Buttons or keys 1-4 choose world types', 'Space advances an epoch', 'R restarts the system', 'Keep stability above 25 through eight epochs']
  },
  {
    id: 'atlas-below',
    title: 'Atlas Below',
    tagline: 'Mine the dark. Build the signal. Find the way home.',
    description: 'A procedural cave expedition with three selectable contracts — Survey Sweep, Crystal Census, and Deep Beacon — plus rank-shaped tunnel width, chamber density, crystal abundance, toxic gas, caches, oxygen upgrades, and persistent contractor mastery.',
    genres: ['Exploration', 'Survival', 'Crafting'],
    added: '2026-09-30', updated: '2026-09-30', version: '1.4',
    featured: false,
    basePopularity: 120,
    cover: 'covers/atlas-below.svg',
    path: 'games/atlas-below/index.html',
    accent: '#7dd3fc', remappable: true,
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Expedition score' },
    controls: ['Remappable directions move', 'Space mines an adjacent resource vein', 'Secondary / C crafts the active contract beacon once its ore, crystal, and cache target is met', 'R restarts the expedition', 'Gamepad left stick + A mine / B craft supported', 'Touch controls on mobile', 'Keys 1-3 or contract buttons switch Survey, Crystal, and Deep expedition contracts', 'Successful extractions unlock rank-shaped cave generation, oxygen, a signal compass, survey caches, gas protection, and contract mastery']
  },
  {
    id: 'aetherstead-colony',
    title: 'Aetherstead Colony',
    tagline: 'Three charters to make a sky-city endure.',
    description: 'A persistent three-charter city-building campaign. Build and upgrade six structure types, exploit farm-water and home-park adjacency, choose charter-specific civic policies, survive deterministic crises, carry charter seals forward, autosave every decision, and link three floating districts into Aetherstead.',
    genres: ['City Builder', 'Colony', 'Simulation', 'Strategy'],
    added: '2026-09-30', updated: '2026-10-01', version: '2.0',
    featured: false,
    basePopularity: 138,
    cover: 'covers/aetherstead-colony.svg',
    path: 'games/aetherstead-colony/index.html',
    accent: '#93c5fd', remappable: true,
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Colony campaign score' },
    controls: ['Tap or click a platform to construct or upgrade the selected building', '1-6 select the six structure types', 'Remappable directions move the platform cursor', 'Primary builds or upgrades the highlighted platform', 'Secondary cycles structures', 'Enter advances one turn', 'Choose one civic policy before construction begins in each charter', 'R restarts the current charter; New Campaign restarts the three-charter arc while preserving earned charter seals']
  },
  {
    id: 'prism-duel',
    title: 'Prism Duel',
    tagline: 'Bank the shot. Read the angle. Beat the room.',
    description: 'A ricochet arena for solo or same-device competitive play. Duel a tracking AI or a second local pilot, bank shots around prism cover, and win a first-to-five skiff battle.',
    genres: ['Multiplayer', 'Competitive', 'Arena', 'Physics'],
    added: '2026-09-30', updated: '2026-09-30', version: '1.1',
    featured: false,
    basePopularity: 124,
    cover: 'covers/prism-duel.svg',
    path: 'games/prism-duel/index.html',
    accent: '#c4b5fd', modes: ['Solo', 'Local Multiplayer'],
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Duel score' },
    controls: ['Mode button or M toggles two-player and VS AI play', 'Player 1: WASD turns/drives, F fires', 'Player 2: Arrow keys turn/drive, / fires in local multiplayer', 'Shots ricochet from walls and prism blocks', 'First pilot to 5 points wins', 'Two gamepads supported in local multiplayer', 'Dual touch controls are available on screen']
  },
  {
    id: 'crownline-tactics',
    title: 'Crownline Tactics',
    tagline: 'Three operatives. Six turns ahead.',
    description: 'A turn-based squad tactics game built around positioning, cover, relay control, limited action points, and readable enemy intent. Capture all three crown relays or eliminate the opposing wardens before the twelfth round.',
    genres: ['Tactical', 'Strategy', 'Turn-Based'],
    added: '2026-09-30',
    featured: false,
    basePopularity: 114,
    cover: 'covers/crownline-tactics.svg',
    path: 'games/crownline-tactics/index.html',
    accent: '#facc15',
    controls: ['Click or tap one of your operatives to select it', 'Select a neighboring tile to move for 1 AP', 'Select an enemy within range 2 to attack for 1 AP', 'Each operative has 2 AP each round', 'End Turn resolves the wardens and refreshes your squad']
  },
  {
    id: 'echo-bazaar',
    title: 'Echo Bazaar',
    tagline: 'Read the market before the market reads you.',
    description: 'A twelve-day trading simulation about cargo space, shifting demand, rumor events, and compounding risk. Buy low, sell high, survive market shocks, and finish with the strongest net worth.',
    genres: ['Economy', 'Simulation', 'Management', 'Strategy'],
    added: '2026-09-30',
    featured: false,
    basePopularity: 112,
    cover: 'covers/echo-bazaar.svg',
    path: 'games/echo-bazaar/index.html', updated: '2026-10-01', version: '1.1',
    accent: '#fb7185',
    controls: ['Tap or click a commodity row to select it', 'Buy and Sell trade one unit at the current price', 'Cargo capacity is limited to 12 units', 'Advance Day refreshes prices and market rumors', 'Finish day 12 with the highest possible net worth']
  },
  {
    id: 'lumen-relay',
    title: 'Lumen Relay',
    tagline: 'Turn the mirrors. Carry the light.',
    description: 'A six-stage laser-routing logic puzzle. Rotate mirrors to bend a live beam through every crystal and into the receiver while avoiding absorbers and minimizing total turns.',
    genres: ['Logic', 'Puzzle', 'Board'],
    added: '2026-09-30',
    featured: false,
    basePopularity: 111,
    cover: 'covers/lumen-relay.svg',
    path: 'games/lumen-relay/index.html', updated: '2026-10-01', version: '1.1',
    accent: '#fde68a',
    controls: ['Click or tap a mirror to rotate it', 'Route the beam through every crystal before the receiver', 'Absorbers stop the beam immediately', 'R restarts the current stage', 'Complete all 6 stages with as few rotations as possible']
  },
  {
    id: 'starweaver-drift',
    title: 'Starweaver Drift',
    tagline: 'Chart the quiet between worlds.',
    description: 'A non-combat space exploration run about fuel, momentum, gravitational anomalies, six survey beacons, and returning your completed constellation to the relay with as much data and hull integrity as possible.',
    genres: ['Space', 'Exploration', 'Simulation'],
    added: '2026-09-30',
    featured: false,
    basePopularity: 110,
    cover: 'covers/starweaver-drift.svg',
    path: 'games/starweaver-drift/index.html', remappable: true, updated: '2026-09-30', version: '1.1',
    accent: '#67e8f9',
    controls: ['Remappable directions steer', 'Primary boosts at extra fuel cost', 'Hold Secondary near a beacon to scan', 'R restarts the survey', 'Gamepad left stick + A/B supported', 'Touch controls on mobile']
  },
  {
    id: 'pulse-archive',
    title: 'Pulse Archive',
    tagline: 'Sync the signal. Preserve the beat.',
    description: 'A four-lane rhythm game built around timing, combo recovery, adaptive scoring, procedural Web Audio pulses, touch controls, keyboard lanes, and gamepad face buttons.',
    genres: ['Rhythm', 'Music', 'Arcade'],
    added: '2026-09-30',
    featured: false,
    basePopularity: 108,
    cover: 'covers/pulse-archive.svg',
    path: 'games/pulse-archive/index.html', updated: '2026-10-01', version: '1.1',
    accent: '#c084fc',
    controls: ['D F J K hit the four lanes', 'Hit notes as they cross the timing line', 'Touch lane buttons on mobile', 'Gamepad face buttons supported', 'Mute preference disables procedural tones']
  },
  {
    id: 'verdant-circuit',
    title: 'Verdant Circuit',
    tagline: 'Design an ecosystem that can survive itself.',
    description: 'A turn-based ecology strategy game. Spend limited energy placing water, seeds, and mycelium, then simulate fourteen turns where neighboring species support or starve one another. Diversity and healthy connections drive the final score.',
    genres: ['Ecology', 'Strategy', 'Simulation', 'Board'],
    added: '2026-09-30',
    featured: false,
    basePopularity: 106,
    cover: 'covers/verdant-circuit.svg',
    path: 'games/verdant-circuit/index.html',
    accent: '#86efac',
    controls: ['Click or tap cells to place the selected organism', '1 / 2 / 3 switch Water, Seed, Mycelium', 'Space advances the ecosystem one turn', 'Plan for diversity and neighboring support', 'Advance starts a new run after turn 14']
  },
  {
    id: 'quiet-protocol',
    title: 'Quiet Protocol',
    tagline: 'Read the room. Cut the signal. Leave unseen.',
    description: 'A compact stealth-puzzle infiltration game. Slip through vision cones, disable security relays, use short-lived signal cloaks, and extract before the facility reaches full alert.',
    objective: 'Disable the required security relays and reach extraction without letting guard vision drive the facility to full alert.',
    genres: ['Stealth', 'Puzzle', 'Action'],
    added: '2026-09-30',
    featured: false,
    basePopularity: 104,
    cover: 'covers/quiet-protocol.svg',
    path: 'games/quiet-protocol/index.html',
    accent: '#5eead4', remappable: true,
    controls: ['WASD / Arrow keys move', 'E hacks nearby relays', 'Space activates a signal cloak when charged', 'Avoid guard vision cones', 'Gamepad left stick + A/B supported']
  },
  {
    id: 'forgeflow',
    title: 'Forgeflow',
    tagline: 'Turn the line. Feed the core. Waste nothing.',
    description: 'An automation-routing puzzle about rotating factory modules to move ore through processors and into the reactor. Build efficient chains, manage heat, and beat each quota before the shift ends.',
    genres: ['Automation', 'Strategy', 'Simulation', 'Puzzle'],
    added: '2026-09-30',
    featured: false,
    basePopularity: 102,
    cover: 'covers/forgeflow.svg',
    path: 'games/forgeflow/index.html',
    accent: '#fb923c',
    controls: ['Click or tap tiles to rotate conveyors', 'Route ore through at least one processor before the reactor', 'Keep jams from overheating the grid', 'R resets the current factory']
  },
  {
    id: 'cloudforge-pinball',
    title: 'Cloudforge Pinball',
    tagline: 'Charge the storm. Keep the sphere alive.',
    description: 'A physics-driven pinball table suspended over a storm forge, with reactive bumpers, combo lanes, multiball charge, keyboard/touch controls, and gamepad-ready flippers.',
    genres: ['Pinball', 'Physics', 'Arcade'],
    added: '2026-09-30', updated: '2026-09-30', version: '1.1',
    featured: false,
    basePopularity: 101,
    cover: 'covers/cloudforge-pinball.svg',
    path: 'games/cloudforge-pinball/index.html',
    accent: '#60a5fa', remappable: true,
    controls: ['Remappable Left / Right control the flippers', 'Primary launches and nudges', 'Gamepad triggers / A supported', 'Touch buttons on mobile', 'R resets the table']
  },
  {
    id: 'mosslight-vale',
    title: 'Mosslight Vale',
    tagline: 'A small world with a long memory.',
    description: 'A long-form top-down exploration RPG spanning six linked regions from Mosslight Village through Silverfen, Sunfall Reach, Moonroot Hollow, and Starbloom Canopy, with NPC quest arcs, real-time combat, collectible relics, six gear tiers, milestone autosaves, five-hub fast travel, persistent world state, and a post-restoration Starshade finale that closes the full campaign.',
    genres: ['RPG', 'Adventure', 'Exploration'],
    added: '2026-09-30', updated: '2026-10-01', version: '1.8',
    featured: false,
    basePopularity: 100,
    cover: 'covers/mosslight-vale.svg',
    path: 'games/mosslight-vale/index.html',
    accent: '#86efac', remappable: true,
    controls: ['Remappable directions move', 'Primary attacks', 'Secondary interacts / talks / saves', 'Shift dashes', 'H uses a potion', 'F cycles unlocked fast-travel hubs including Starbloom Canopy', 'I opens the field-pack inventory', 'Major region restorations autosave automatically', 'Touch controls on mobile']
  },
  {
    id: 'gravity-foundry',
    title: 'Gravity Foundry',
    tagline: 'Bend the orbit. Build the path.',
    description: 'A physics puzzle about launching a probe through gravitational fields. Sweep every energy core, avoid planetary collisions, and enter the stabilized gate using as few launches as possible.',
    genres: ['Physics', 'Puzzle', 'Simulation'],
    added: '2026-09-30',
    featured: false,
    basePopularity: 98,
    cover: 'covers/gravity-foundry.svg',
    path: 'games/gravity-foundry/index.html',
    accent: '#67e8f9',
    controls: ['Drag backward from the probe to aim', 'Release to launch', 'Collect every core before entering the gate', 'R resets the field', 'Pointer and touch controls supported']
  },
  {
    id: 'hexbound-tactics',
    title: 'Hexbound Tactics',
    tagline: 'Play the lane. Break the citadel.',
    description: 'A compact card-battle tactics game with three contested lanes, an energy economy, a rotating hand, simultaneous combat resolution, and an AI rival that builds its own board each turn.',
    genres: ['Card', 'Strategy', 'Board'],
    added: '2026-09-30',
    featured: false,
    basePopularity: 97,
    cover: 'covers/hexbound-tactics.svg',
    path: 'games/hexbound-tactics/index.html',
    accent: '#c4b5fd',
    controls: ['Select a card from your hand', 'Choose a lane to deploy it', 'Spend up to 4 energy each turn', 'End Turn to resolve combat', 'Touch and mouse supported']
  },
  {
    id: 'harbor-pulse',
    title: 'Harbor Pulse',
    tagline: 'Route the fleet. Protect the harbor.',
    description: 'A real-time harbor-management simulation. Assign color-coded arrivals to matching berths, prevent collisions, keep ships from abandoning the harbor, and build the highest 90-second credit total.',
    genres: ['Simulation', 'Management', 'Arcade'],
    added: '2026-09-30',
    featured: false,
    basePopularity: 96,
    cover: 'covers/harbor-pulse.svg',
    path: 'games/harbor-pulse/index.html',
    accent: '#22d3ee',
    controls: ['Tap or click a ship to select it', 'Tap its matching colored berth to route it', 'Avoid collisions and abandoned arrivals', 'Protect your reputation for 90 seconds']
  },
  {
    id: 'rift-relay',
    title: 'Rift Relay',
    tagline: 'Two players. One orb. Hold the link.',
    description: 'A same-device two-player cooperative arena game. Coordinate two runners, protect the shared relay orb, dodge moving hazards, and carry the charge through eight rotating rifts before the team shield or clock collapses.',
    genres: ['Co-op', 'Multiplayer', 'Arcade'],
    added: '2026-09-30', updated: '2026-09-30', version: '1.1',
    featured: false,
    basePopularity: 96,
    cover: 'covers/rift-relay.svg',
    path: 'games/rift-relay/index.html',
    accent: '#c4b5fd', remappable: true,
    controls: ['Player 1 uses remappable directional controls', 'Player 2 uses Arrow keys', 'Touch the orb to carry it', 'Stay close while carrying the shared charge', 'Reach all 8 rifts before time or shield runs out']
  },
  {
    id: 'skyhook-sprint',
    title: 'Skyhook Sprint',
    tagline: 'Run the skyline. Catch the anchor. Never touch the void.',
    description: 'A momentum platformer built around jumps and a quick-release grappling hook. Chain swings between rooftop anchors, collect skyline stars, and race for a faster finish.',
    genres: ['Platformer', 'Action', 'Speedrun'],
    added: '2026-09-29',
    featured: false,
    basePopularity: 95,
    cover: 'covers/skyhook-sprint.svg',
    path: 'games/skyhook-sprint/index.html',
    accent: '#38bdf8', remappable: true,
    controls: ['← / → move', 'Space jumps', 'E attaches/releases the nearest hook', 'R restarts', 'Gamepad left stick + A/B supported', 'Touch controls on mobile']
  },
  {
    id: 'neon-stack',
    title: 'Neon Stack',
    tagline: 'Stack fast. Clear clean. Chase the glow.',
    description: 'A crisp falling-block puzzler with escalating speed, combo scoring, ghost placement, keyboard and touch controls, and instant restarts.',
    genres: ['Puzzle', 'Arcade'],
    added: '2026-09-29', updated: '2026-09-30', version: '1.1',
    featured: false,
    basePopularity: 94,
    cover: 'covers/neon-stack.svg',
    path: 'games/neon-stack/index.html',
    accent: '#8b5cf6', remappable: true,
    controls: ['Remappable Left / Right move', 'Remappable Down soft-drops', 'Secondary / Z rotates', 'Primary hard-drops', 'P pauses', 'Gamepad D-pad + face buttons supported', 'Touch controls on mobile']
  },
  {
    id: 'circuit-rush',
    title: 'Circuit Rush',
    tagline: 'Own the checkpoint line.',
    description: 'A three-lap top-down circuit racer with ordered checkpoint gates, three live AI rivals, boost pads, position tracking, off-track grip loss, remappable controls, gamepad support, and local best-time chasing.',
    genres: ['Racing', 'Arcade', 'Time Trial', 'Competitive'],
    added: '2026-09-29', updated: '2026-10-01', version: '2.1',
    featured: false,
    basePopularity: 176,
    cover: 'covers/circuit-rush.svg',
    path: 'games/circuit-rush/index.html',
    accent: '#22d3ee', remappable: true,
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Race score' },
    controls: ['Remappable Up accelerates and Down brakes/reverses', 'Remappable Left / Right steers', 'Follow glowing checkpoints in order and use cyan boost pads', 'P pauses and R restarts', 'Touch controls on mobile', 'Gamepad left stick supported']
  },
  {
    id: 'bastion-bloom', title: 'Bastion Bloom', tagline: 'Plant the defense. Grow the line. Hold ten waves.',
    description: 'A ten-wave tower-defense campaign with Bloom damage towers, Frost slow towers, Spore splash towers, runners, brutes, two boss assaults, upgrades, speed controls, and remappable keyboard play.',
    genres: ['Tower Defense', 'Strategy', 'Defense'], added: '2026-09-29', updated: '2026-09-30', version: '1.5', featured: false, basePopularity: 181,
    cover: 'covers/bastion-bloom.svg', path: 'games/bastion-bloom/index.html', accent: '#a3e635', remappable: true,
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Garden campaign score' },
    controls: ['Remappable Left / Right selects a garden node', 'Remappable Up / Down cycles Bloom, Frost, and Spore towers', 'Primary builds or upgrades the selected node', 'Secondary starts the next wave', 'Click or tap nodes and controls for pointer/touch play', 'P pauses, T toggles 1×/2× speed, R restarts the campaign']
  },
  {
    id: 'emberfield-survival',
    title: 'Emberfield Survival',
    tagline: 'Move, evolve, and keep the last ember alive.',
    description: 'A survival-arena run with automatic targeting, dash movement, escalating swarms, collectible embers, and mid-run upgrades that reshape your build.',
    genres: ['Survival', 'Action', 'Roguelite'],
    added: '2026-09-29',
    featured: false,
    basePopularity: 91,
    cover: 'covers/emberfield-survival.svg',
    path: 'games/emberfield-survival/index.html',
    remappable: true, accent: '#f97316',
    controls: ['Remappable directions move', 'Space dashes', 'Weapons automatically target the nearest threat', 'Choose upgrades when you level', 'Gamepad left stick + A dash supported', 'Touch controls on mobile']
  },
  {
    id: 'vector-league',
    title: 'Vector League',
    tagline: 'Ninety seconds. Five goals. Own the angle.',
    description: 'A fast one-on-one neon arena sport against an AI rival. Chase, bump, angle your shots, and score through the opposing gate before the clock expires.',
    genres: ['Sports', 'Competitive', 'Arcade'],
    added: '2026-09-29',
    featured: false,
    basePopularity: 90,
    cover: 'covers/vector-league.svg',
    path: 'games/vector-league/index.html',
    remappable: true, accent: '#22d3ee',
    controls: ['Remappable directions move', 'Space kicks when near the ball', 'Aim vertical shot angle while moving up/down', 'First to 5 or leader at 90 seconds wins', 'Gamepad left stick + A supported', 'Touch controls on mobile']
  },
  {
    id: 'orbit-breaker',
    title: 'Orbit Breaker',
    tagline: 'Hold the line above a collapsing world.',
    description: 'A fast screen-wrapping space-rock shooter where only direct asteroid collisions damage your three-point shield. Destroy incoming rocks for score, survive escalating waves, and chase a persistent local best.',
    objective: 'Destroy asteroids and survive for the highest score you can. Your shield only drops on direct ship collisions; asteroids that fly past the bottom of the screen do not damage you.',
    genres: ['Space', 'Shooter', 'Arcade'],
    added: '2026-09-29', updated: '2026-10-02', version: '1.1',
    featured: false,
    basePopularity: 89,
    cover: 'covers/orbit-breaker.svg',
    path: 'games/orbit-breaker/index.html',
    accent: '#22d3ee', remappable: true,
    controls: ['Remappable Left / Right moves the ship', 'Primary fires', 'Direct asteroid collisions remove one shield point', 'Asteroids that leave the bottom of the screen do not damage the ship', 'A short invulnerability window follows each hit', 'P pauses', 'Touch buttons on mobile', 'Gamepad left stick + A supported']
  },
  {
    id: 'rune-depths',
    title: 'Rune Depths',
    tagline: 'Five depths. Three relic paths. One way back.',
    description: 'A five-depth procedural dungeon campaign with deterministic mazes, four sigils per floor, Shade/Wisp/Brute enemies, autosaved active delves, three pure relic mastery paths, potions, persistent best scores, and full-run mastery.',
    genres: ['Dungeon', 'Roguelite', 'Adventure'],
    added: '2026-09-29', updated: '2026-10-01', version: '2.1',
    featured: false,
    basePopularity: 178,
    cover: 'covers/rune-depths.svg',
    path: 'games/rune-depths/index.html',
    accent: '#f59e0b', remappable: true,
    scoreMeta: { unit: 'pts', direction: 'high', label: 'Delve score' },
    controls: ['Remappable directional keys move one dungeon tile', 'Primary attacks adjacent enemies', 'Secondary drinks a potion', 'Clear four sigils and reach the gate on each of five depths', 'Choose Heart, Edge, or Flask relics between floors; repeat one family for a pure mastery path', 'Active delves autosave locally and can resume after reload', 'Touch controls and gamepad supported', 'R starts a fresh run']
  }
];

window.WWG_GAMES.forEach(game => {
  if (!game.scoreMeta) game.scoreMeta = { unit: 'pts', direction: 'high', label: 'Local score' };
});