const fs=require('fs'),path=require('path'),vm=require('vm');
function cls(){return{toggle(){},add(){},remove(){},contains(){return false}}}
function el(id=''){return{id,innerHTML:'',textContent:'',value:'',checked:false,hidden:false,style:{setProperty(){},},dataset:{},classList:cls(),src:'',alt:'',href:'',width:0,height:0,children:[],addEventListener(){},removeEventListener(){},showModal(){},close(){},setPointerCapture(){},requestFullscreen(){},getBoundingClientRect(){return{left:0,top:0,width:960,height:540}},getContext(){return ctx2d},querySelectorAll(){return[]},querySelector(){return el()},appendChild(x){this.children.push(x);return x},remove(){}}}
const ctx2d=new Proxy({}, {get(t,p){if(p in t)return t[p];if(p==='measureText')return()=>({width:10});if(p==='createLinearGradient'||p==='createRadialGradient')return()=>({addColorStop(){}});return()=>{}},set(t,p,v){t[p]=v;return true}});
function makeContext(){
 const elements=new Map();const get=id=>{if(!elements.has(id))elements.set(id,el(id));return elements.get(id)};const canvas=get('c');canvas.getContext=()=>ctx2d;
 const listeners={};let raf=null;let timers=[];let store={};
 const doc={documentElement:{classList:cls(),style:{setProperty(){}}},body:el('body'),querySelector(s){if(s.startsWith('#'))return get(s.slice(1));return el(s)},querySelectorAll(){return[]},getElementById:get,createElement:()=>el()};
 const context={console,Math,Date,JSON,URLSearchParams,document:doc,window:null,parent:{postMessage(){}},navigator:{serviceWorker:{register(){return Promise.resolve()}},getGamepads(){return[]}},location:{search:'',protocol:'http:',href:'',reload(){}},localStorage:{getItem(k){return Object.prototype.hasOwnProperty.call(store,k)?store[k]:null},setItem(k,v){store[k]=String(v)},removeItem(k){delete store[k]}},innerWidth:960,innerHeight:540,devicePixelRatio:1,performance:{now:()=>0},requestAnimationFrame(fn){raf=fn;return 1},cancelAnimationFrame(){},setTimeout(fn){timers.push(fn);return timers.length},clearTimeout(){},setInterval(fn){timers.push(fn);return timers.length},clearInterval(){},addEventListener(type,fn){(listeners[type]??=[]).push(fn)},removeEventListener(){},dispatch(type,event={}){for(const fn of listeners[type]||[])fn(event)},getComputedStyle(){return{}},alert(){},confirm(){return true},Image:function(){},AudioContext:function(){},webkitAudioContext:function(){}};context.window=context;context.globalThis=context;
 return{context,runFrames(n=5){for(let i=1;i<=n;i++){const fn=raf;raf=null;if(fn)fn(i*16.67)}},elements,store,listeners,timers};
}
let failures=0;for(const d of fs.readdirSync('games').sort()){
 const f=path.join('games',d,'index.html'),html=fs.readFileSync(f,'utf8'),scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);
 const h=makeContext();try{vm.createContext(h.context);for(const s of scripts)vm.runInContext(s,h.context,{filename:f});h.runFrames(8);console.log('PASS game boot',d)}catch(e){failures++;console.error('FAIL game boot',d,e.stack)}
}
// platform homepage boot
try{const h=makeContext();for(const id of ['gameGrid','emptyState','categoryChips','recentGrid','favoriteGrid','profileStats','achievementGrid','recommendationGrid','recommendationNote','challengeGrid','challengeNote','scoreBoard','heroTitle','heroDescription','heroPlay','heroArt','gameCount','genreCount','searchInput','sortSelect','profileButton','clearData','reducedMotion','mutePreference','profileDialog'])h.elements.set(id,el(id));vm.createContext(h.context);vm.runInContext(fs.readFileSync('js/games.js','utf8'),h.context,{filename:'js/games.js'});vm.runInContext(fs.readFileSync('js/app.js','utf8'),h.context,{filename:'js/app.js'});console.log('PASS platform homepage boot')}catch(e){failures++;console.error('FAIL platform homepage',e.stack)}
// game detail boot against featured game
try{const h=makeContext();h.context.location.search='?id=quiet-protocol';for(const id of ['gameGenre','gameTitle','gameDescription','gameCover','controlsList','gameDate','gameBadge','footerGame','gameFrame','favoriteButton','fullscreenButton','gameFrameWrap','ratingControl','ratingNote','localBest'])h.elements.set(id,el(id));vm.createContext(h.context);vm.runInContext(fs.readFileSync('js/games.js','utf8'),h.context,{filename:'js/games.js'});vm.runInContext(fs.readFileSync('js/game-page.js','utf8'),h.context,{filename:'js/game-page.js'});console.log('PASS game detail boot')}catch(e){failures++;console.error('FAIL game detail',e.stack)}
if(failures){console.error(`${failures} smoke failures`);process.exit(1)}console.log('All smoke harness checks passed.');
