from playwright.sync_api import sync_playwright
from pathlib import Path
import json
ROOT=Path('.').resolve();INPUT=(ROOT/'assets/wwg-input.js').read_text();MAP={'up':'KeyI','down':'KeyK','left':'KeyJ','right':'KeyL','primary':'KeyF','secondary':'KeyH'}
def pre():
 data=json.dumps({'wwg:keymap':json.dumps(MAP)});return f"<script>const __s={data};Object.defineProperty(window,'localStorage',{{value:{{getItem:k=>Object.prototype.hasOwnProperty.call(__s,k)?__s[k]:null,setItem:(k,v)=>__s[k]=String(v),removeItem:k=>delete __s[k]}},configurable:true}});window.__events=[];window.postMessage=(d)=>window.__events.push(d);</script>"
def raw(slug):
 s=(ROOT/'games'/slug/'index.html').read_text().replace('<script src="../../assets/wwg-input.js"></script>',f'<script>{INPUT}</script>');return s.replace('<script>',pre()+'<script>',1)
with sync_playwright() as pw:
 b=pw.chromium.launch(headless=True,executable_path='/usr/bin/chromium',args=['--no-sandbox','--disable-gpu']);out={}
 for slug,var in [('frostline-rescue','player.x'),('atlas-below','p.x'),('quiet-protocol','p.x'),('skyhook-sprint','p.x'),('mosslight-vale','player.x'),('glasswing-polo','p1.x'),('vector-league','p.x'),('emberfield-survival','p.x'),('pulsevine-parkour','p.x')]:
  p=b.new_page(viewport={'width':1000,'height':700});p.set_content(raw(slug),wait_until='domcontentloaded');p.wait_for_timeout(90);before=p.evaluate(var);p.keyboard.down('KeyL');p.wait_for_timeout(150);p.keyboard.up('KeyL');after=p.evaluate(var);assert after>before,(slug,before,after);out[slug]=(before,after);p.close()
 p=b.new_page(viewport={'width':980,'height':700});p.set_content(raw('lantern-line'),wait_until='domcontentloaded');p.wait_for_timeout(60);before=p.evaluate('speed');p.keyboard.down('KeyI');p.wait_for_timeout(150);p.keyboard.up('KeyI');after=p.evaluate('speed');assert after>before;out['lantern-line']=(before,after);p.close()
 p=b.new_page(viewport={'width':980,'height':700});p.set_content(raw('chronofold-courier'),wait_until='domcontentloaded');p.wait_for_timeout(50);before=p.evaluate('player.x');p.keyboard.press('KeyL');after=p.evaluate('player.x');assert after>before;p.keyboard.press('KeyF');assert p.evaluate('echoes.length')==1;out['chronofold-courier']=(before,after);p.close()
 p=b.new_page(viewport={'width':980,'height':700});p.set_content(raw('circuit-rush'),wait_until='domcontentloaded');p.wait_for_timeout(50);before=p.evaluate('car.v');p.keyboard.down('KeyI');p.wait_for_timeout(160);p.keyboard.up('KeyI');after=p.evaluate('car.v');assert after>before;out['circuit-rush']=(before,after);p.close()
 p=b.new_page(viewport={'width':980,'height':700});p.set_content(raw('orbit-breaker'),wait_until='domcontentloaded');p.wait_for_timeout(50);before=p.evaluate('shots.length');p.keyboard.press('KeyF');p.wait_for_timeout(20);after=p.evaluate('shots.length');assert after>before;out['orbit-breaker']=(before,after);p.close()
 p=b.new_page(viewport={'width':980,'height':700});p.set_content(raw('riftwake-regatta'),wait_until='domcontentloaded');p.wait_for_timeout(50);before=p.evaluate('boat.a');p.keyboard.down('KeyL');p.wait_for_timeout(150);p.keyboard.up('KeyL');after=p.evaluate('boat.a');assert after>before;out['riftwake-regatta']=(before,after);p.close()
 p=b.new_page(viewport={'width':980,'height':700});p.set_content(raw('stoneveil-ascent'),wait_until='domcontentloaded');p.wait_for_timeout(50);before=p.evaluate('selected');p.keyboard.press('KeyL');after=p.evaluate('selected');assert after!=before or p.evaluate('reachable().length')==1;p.keyboard.press('KeyF');p.wait_for_timeout(380);assert p.evaluate('cur')!=0;out['stoneveil-ascent']=(before,after);p.close()
 p=b.new_page(viewport={'width':980,'height':700});p.set_content(raw('tidal-foundry'),wait_until='domcontentloaded');p.wait_for_timeout(50);before=p.evaluate('tiles[cursor].m');p.keyboard.press('KeyF');after=p.evaluate('tiles[cursor].m');assert after!=before;out['tidal-foundry']=(before,after);p.close()
 p=b.new_page(viewport={'width':980,'height':700});p.set_content(raw('rootsong-architect'),wait_until='domcontentloaded');p.wait_for_timeout(50);before=p.evaluate('cursor[0]');p.keyboard.press('KeyF');assert p.evaluate('grown.size')>1;p.keyboard.press('KeyL');after=p.evaluate('cursor[0]');assert after>before;out['rootsong-architect']=(before,after);p.close()
 # New Tessera secondary/primary mapping.
 p=b.new_page(viewport={'width':900,'height':750});p.set_content(raw('tessera-commons'),wait_until='domcontentloaded');p.wait_for_timeout(50);p.keyboard.press('KeyH');assert p.evaluate('pick')==1;p.evaluate('cursor=[2,2]');p.keyboard.press('KeyF');assert p.evaluate('board.filter(Boolean).length')==1;out['tessera-commons']=(0,1);p.close()
 # Cloudforge custom left/right/primary.
 p=b.new_page(viewport={'width':900,'height':700});p.set_content(raw('cloudforge-pinball'),wait_until='domcontentloaded');p.wait_for_timeout(50);p.keyboard.down('KeyJ');assert p.evaluate('left') is True;p.keyboard.up('KeyJ');p.keyboard.press('KeyF');assert p.evaluate('balls.length')==1;out['cloudforge-pinball']=(0,1);p.close()
 # Neon Stack custom movement/hard drop/rotate.
 p=b.new_page(viewport={'width':800,'height':700});p.set_content(raw('neon-stack'),wait_until='domcontentloaded');p.wait_for_timeout(50);before=p.evaluate('piece.x');p.keyboard.press('KeyL');after=p.evaluate('piece.x');assert after>=before;p.keyboard.press('KeyH');p.keyboard.press('KeyF');out['neon-stack']=(before,after);p.close()

 p=b.new_page(viewport={'width':900,'height':700});p.set_content(raw('mirrormesh-relay'),wait_until='domcontentloaded');p.wait_for_timeout(50);before=p.evaluate('mirrors[0][2]');p.keyboard.press('KeyF');after=p.evaluate('mirrors[0][2]');assert after!=before;out['mirrormesh-relay']=(before,after);p.close()
 p=b.new_page(viewport={'width':900,'height':700});p.set_content(raw('hushwave-operator'),wait_until='domcontentloaded');p.wait_for_timeout(50);before=p.evaluate('+els[0].value');p.keyboard.press('KeyL');after=p.evaluate('+els[0].value');assert after>before;out['hushwave-operator']=(before,after);p.close()
 p=b.new_page(viewport={'width':1000,'height':700});p.set_content(raw('kiteglass-drift'),wait_until='domcontentloaded');p.wait_for_timeout(70);before=p.evaluate('y');p.keyboard.down('KeyI');p.wait_for_timeout(190);p.keyboard.up('KeyI');after=p.evaluate('y');assert after<before,(before,after);out['kiteglass-drift']=(before,after);p.close()
 p=b.new_page(viewport={'width':900,'height':720});p.set_content(raw('runelight-locksmith'),wait_until='domcontentloaded');p.wait_for_timeout(70);before=p.evaluate('selected');p.keyboard.press('KeyL');after=p.evaluate('selected');assert after!=before;out['runelight-locksmith']=(before,after);p.close()
 p=b.new_page(viewport={'width':1000,'height':700});p.set_content(raw('starweaver-drift'),wait_until='domcontentloaded');p.wait_for_timeout(60);before=p.evaluate('ship.x');p.keyboard.down('KeyL');p.wait_for_timeout(180);p.keyboard.up('KeyL');after=p.evaluate('ship.x');assert after>before,(before,after);out['starweaver-drift']=(before,after);p.close()
 p=b.new_page(viewport={'width':1000,'height':700});p.set_content(raw('windward-cargo'),wait_until='domcontentloaded');p.wait_for_timeout(60);before=p.evaluate('p.vx');p.keyboard.down('KeyI');p.wait_for_timeout(180);p.keyboard.up('KeyI');after=p.evaluate('p.vx');assert after>before,(before,after);out['windward-cargo']=(before,after);p.close()
 b.close();print({'remappableGames':len(out),'checks':out})
